/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CoreTelephonyClient.h
  https://headers.82flex.com/view/18.6_22G86/System/Library/Frameworks/CoreTelephony.framework/CoreTelephony/CoreTelephonyClient.h
  https://headers.82flex.com/diff/17.0_21A329...18.6_22G86/System/Library/Frameworks/CoreTelephony.framework/CoreTelephony/CoreTelephonyClient.h
*/


//#import <CoreTelephony/CoreTelephony-Structs.h>
#import "CTXPCServiceSubscriptionInfo.h"
#import "CTXPCContexts.h"
#import "CTXPCServiceSubscriptionContext.h"
#import "CTServiceDescriptorContainer.h"
#import "CTServiceDescriptor.h"
#import "CTActivationPolicyState.h"
#import "CTDataConnectionAvailabilityStatus.h"
#import "CTMobileEquipmentInfoList.h"
#import "CTMobileEquipmentInfo.h"
#import "CTSimLabel.h"
#import "CTSupportedMaxDataRates.h"
#import "CTPhoneNumberInfo.h"
#import "CTRegistrationDisplayStatus.h"
#import "CTDataStatusBasic.h"
#import "CTRatSelection.h"
#import "CTDataConnectionStatus.h"
#import "CTSignalStrengthInfo.h"
#import "CTSignalStrengthMeasurements.h"
#import "CTIMSRegistrationStatus.h"
#import "CTNRStatus.h"
#import "CTPNRContextInfo.h"
#import "CTCallCapabilities.h"
#import "CTNetworkSelectionInfo.h"
#import "CTBandInfo.h"
#import "CTCellInfo.h"
#import "CTCellIdInfo.h"
#import "CTDataStatus.h"
#import "CTSimHardwareInfo.h"
#import "CTPhoneBookEntry.h"
#import "CTTetheringStatus.h"
#import "CTEmergencyModeResult.h"
#import "CTCellularUsageWorkspaceInfo.h"
#import "CTBundle.h"

@class CoreTelephonyClientMux;

typedef struct {
    BOOL privateRelayEnabled; // iCloud专用代理是否开启
    BOOL limitIPTrackingEnabled; // 数据卡是否开启 限制IP地址跟踪
} CTPrivacyProxyState;

typedef struct {
    BOOL field1; // TODO
    BOOL field2; // TODO
} CTReliableNetworkFallbackState;


@interface CoreTelephonyClient : NSObject {

    id fDelegateAddr;
    unsigned long long fOsStateHandle;
    id _delegate;
//    queue* _userQueue;
    CoreTelephonyClientMux* _mux;
}
@property (assign) void* fDataAssertion;
//@property (assign,nonatomic) queue* userQueue;                          //@synthesize userQueue=_userQueue - In the implementation block
@property (nonatomic,retain) CoreTelephonyClientMux * mux;              //@synthesize mux=_mux - In the implementation block
//@property (assign,nonatomic,__weak) id delegate;                        //@synthesize delegate=_delegate - In the implementation block
-(id)init;
-(void)dealloc;
-(id)delegate;
-(void)setDelegate:(id)delegate; // 设置代理
-(BOOL)supportsCellular API_AVAILABLE(ios(15.0)); // 是否支持蜂窝网络
-(CoreTelephonyClientMux *)mux;
+(id)sharedMultiplexer;
-(void)ping:(/*^block*/id)arg1 ;
//-(id)initWithQueue:(dispatch_queue_sRef)arg1 ;
-(NSNumber *)getReleaseCandidateFlag API_AVAILABLE(ios(15.4)); // 获取是不是RC状态的flag 返回0 需要iOS 15.4+
-(NSNumber *)isFactoryDebugEnabled:(NSError **)error API_AVAILABLE(ios(15.4)); // 工厂测试模式已启用 需要iOS 15.4+
-(void)cacheValue:(id)arg1 forSelector:(SEL)selector ;
-(id)cachedValueForSelector:(SEL)selector ;
-(BOOL)supportsRequestWithSelector:(SEL)selector ;
-(BOOL)supportsSelector:(SEL)selector withContext:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error ;
-(id)proxyWithErrorHandler:(/*^block*/id)arg1 ;
-(id)synchronousProxyWithErrorHandler:(/*^block*/id)arg1 ;
//-(void)getDeviceInfo:(/*^block*/id)arg1 ;
- (void)getDeviceInfo:(void (^)(NSDictionary *info, NSError *error))completion API_AVAILABLE(ios(15.0)); // 获取设备信息
- (CTActivationPolicyState *)getActivationPolicyState:(NSError **)error API_AVAILABLE(ios(14.0)); // 获取运营商锁状态 有锁无锁 需要额外权利
- (BOOL)isSmartDataModeSupported:(NSError **)error API_AVAILABLE(ios(14.0)) NS_SWIFT_NOTHROW; // 设备是否支持自动5G 间接判断设备是否支持5G
- (long long)getDualSimCapability:(NSError **)error; // 设备支持双卡情况
- (BOOL)supportsEmbeddedSIM API_AVAILABLE(ios(16.0)); // 是否支持eSIM 需要iOS 16.0+
- (NSNumber *)isEmbeddedSIMOnlyConfig:(NSError **)error API_AVAILABLE(ios(16.0)); // 判断是否是纯eSIM机型
- (NSNumber *)checkEmbeddedSimHealthWithError:(NSError **)error API_AVAILABLE(ios(16.0)); // 检查eSIM健康状况
- (NSNumber *)isAnySimReadyWithError:(NSError **)error API_AVAILABLE(ios(16.4)); // 是否有SIM卡准备完毕 无需额外权利
-(void)getSIMTrayStatus:(/*^block*/id)arg1; // 获取SIM卡槽状态 异步方法
- (NSString *)getSIMTrayStatusOrError:(NSError **)error; // 获取SIM卡槽状态 同步方法
-(void)copyPriVersion:(id)arg1 completion:(/*^block*/id)arg2 ; // TODO 获取PRI信息 CDMA的东西 返回的是nil
//-(_CTAssertionType*)createCTAssertionForConnectionType:(int)arg1 allocator:(CFAllocatorRef)arg2 proxy:(id)arg3 ;
-(CTServiceDescriptorContainer *)getDescriptorsForDomain:(long long)domain error:(id*)error; // 通过domain获取CTServiceDescriptorContainer
-(void)getDescriptorsForDomain:(long long)arg1 completion:(/*^block*/id)arg2 ;
-(void)getActiveContextsWithCallback:(/*^block*/id)arg1 ;
- (CTXPCServiceSubscriptionContext *)getPreferredDataSubscriptionContextSync:(id*)error; // 获取当前的数据卡context
- (CTXPCServiceSubscriptionContext *)getUserDefaultVoiceSubscriptionContext:(NSError **)error API_AVAILABLE(ios(13.0)); // 获取默认语音号码的Context
-(void)getCurrentDataSubscriptionContext:(/*^block*/id)arg1 ;
-(CTXPCServiceSubscriptionContext *)getCurrentDataSubscriptionContextSync:(id*)error; // 获取当前正在使用的数据卡的context
- (CTXPCServiceSubscriptionInfo *)getSubscriptionInfoWithError:(NSError **)error; // 获取的是CTXPCServiceSubscriptionInfo 内部包含[CTXPCServiceSubscriptionContext]列表 context是完整的
- (CTXPCContexts *)getActiveContexts:(NSError **)error; // 获取活跃的context列表 返回CTXPCContexts context是完整的
-(void)getPreferredDataServiceDescriptor:(/*^block*/id)arg1 ;
- (CTServiceDescriptor *)getPreferredDataServiceDescriptorSync:(id*)error; // 获取选中数据卡的Descriptor
-(void)getPreferredDataSubscriptionContext:(/*^block*/id)arg1 ;
-(void)getCurrentDataServiceDescriptor:(/*^block*/id)arg1 ;
- (CTServiceDescriptor *)getCurrentDataServiceDescriptorSync:(id*)error; // 获取当前使用的蜂窝数据卡的Descriptor
-(void)getSubscriptionInfo:(/*^block*/id)arg1 ; // 一个闭包返回参数 返回nil
- (NSError *)getPacketContextCount:(uint32_t *)count; // TODO
-(void)getActiveConnections:(id)arg1 completion:(/*^block*/id)arg2 ;
-(NSArray <NSString *> *)getActiveConnections:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error ; // 获取当前卡槽激活的数据服务类型
-(NSString *)getTypeAllocationCode:(CTServiceDescriptor *)descriptor error:(NSError **)error API_AVAILABLE(ios(13.0)); // 获取当前卡槽使用的Type Allocation Code 就是IMEI前8位
-(NSString *)getLocalizedOperatorName:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取网络名称
-(NSString *)getOperatorName:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error API_AVAILABLE(ios(16.0)); // 获取网络名称 跟上面的方法获取的是一样的内容
-(void)copyOperatorName:(id)arg1 completion:(/*^block*/id)arg2 ;
-(NSString *)getEnglishCarrierNameFor:(NSString *)operatorName error:(NSError **)error API_AVAILABLE(ios(15.0)); // 获取运营商的英文名
-(CTBandInfo *)getBandInfo:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error API_AVAILABLE(ios(14.0)); // 获取基带信息
-(CTNetworkSelectionInfo *)copyNetworkSelectionInfo:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取搜索运营商网络的结果
-(CTIMSRegistrationStatus *)getIMSRegistrationStatus:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取IMS状态
-(void)getSimLabel:(id)arg1 completion:(/*^block*/id)arg2; // 获取SIM卡标签实例 异步方法
-(CTSimLabel *)getSimLabel:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取SIM卡标签实例 同步方法
-(void)copyLabel:(CTXPCServiceSubscriptionContext *)context completion:(/*^block*/id)completion; // 异步方法 复制当前卡的标签
-(NSString *)copyLabel:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 同步方法 获取卡槽的标签
-(void)getSubscriptionUserFacingName:(id)arg1 completion:(/*^block*/id)arg2 API_AVAILABLE(ios(15.0)); // 获取用户看到的卡标签名称 异步方法
-(NSString *)getSubscriptionUserFacingName:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error API_AVAILABLE(ios(15.0)); // 获取用户看到的卡标签名称 同步方法
-(void)getShortLabel:(id)arg1 completion:(/*^block*/id)arg2;
-(NSString *)getShortLabel:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取SIM卡标签短的名称 无卡/纯单卡设备/iPad蜂窝版 返回错误35
-(void)setLabel:(id)arg1 label:(id)label completion:(/*^block*/id)arg3 ;
-(void)setLabel:(id)arg1 label:(id)label error:(id*)arg3 ;
-(void)copyGid1:(CTXPCServiceSubscriptionContext *)context completion:(/*^block*/id)arg2 ;
-(void)copyGid2:(CTXPCServiceSubscriptionContext *)context completion:(/*^block*/id)arg2 ;
- (NSString *)copyGid1:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error;  // 获取GID 1
- (NSString *)copyGid2:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error;  // 获取GID 2
-(void)copySIMIdentity:(id)arg1 completion:(/*^block*/id)arg2;
- (NSString *)copySIMIdentity:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取ICCID
- (NSString *)copyMobileSubscriberIdentity:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取IMSI
-(void)copyMobileCountryCode:(id)arg1 completion:(/*^block*/id)arg2 ;
- (NSString *)copyMobileCountryCode:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取连接网络的 MCC
- (NSString *)copyMobileSubscriberNetworkCode:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取SIM卡的MNC
-(void)copyMobileSubscriberCountryCode:(id)arg1 completion:(/*^block*/id)arg2 ;
-(NSString *)copyMobileSubscriberCountryCode:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取SIM卡的MCC
-(void)copyMobileSubscriberIdentity:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)copyMobileSubscriberNetworkCode:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)copyMobileNetworkCode:(id)arg1 completion:(/*^block*/id)arg2 ;
- (NSString *)copyMobileNetworkCode:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取连接网络的 MNC
-(void)copyRegistrationStatus:(id)arg1 completion:(/*^block*/id)arg2;
- (NSString *)copyRegistrationStatus:(CTXPCServiceSubscriptionContext *) context error:(NSError **)error ; // 获取当前卡的注册状态
-(void)copyRegistrationDisplayStatus:(CTXPCServiceSubscriptionContext *) context completion:(/*^block*/id)arg2 ;
- (CTRegistrationDisplayStatus *)copyRegistrationDisplayStatus:(CTXPCServiceSubscriptionContext *) context error:(NSError **)error; // 获取当前的卡注册状态的数据模型
-(void)copyServingPlmn:(id)arg1 completion:(/*^block*/id)arg2 API_AVAILABLE(ios(13.0));
- (NSString *)copyServingPlmn:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error API_AVAILABLE(ios(13.0)); // 同步方法 获取PLMN数据
-(void)copyRadioAccessTechnology:(id)arg1 completion:(/*^block*/id)arg2;
- (NSString *)copyRadioAccessTechnology:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error ; // 获取当前使用的无线技术
- (CTSupportedMaxDataRates *)getSupportedDataRates:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 同步方法 获取支持蜂窝网络类型
-(void)getSupportedDataRates:(CTXPCServiceSubscriptionContext *)context completion:(/*^block*/id)arg2; // 异步方法 获取支持蜂窝网络类型
- (NSNumber *)getSupports5G:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error API_AVAILABLE(ios(14.0)); // 当前卡槽的卡是否支持5G
- (NSNumber *)getSupports5GStandalone:(CTServiceDescriptor *)descriptor error:(NSError **)error API_AVAILABLE(ios(14.0)); // 是否支持5G SA 需要套餐卡支持5G
- (CTNRStatus *)getNRDisableStatus:(CTServiceDescriptor *)descriptor error:(NSError **)error API_AVAILABLE(ios(14.0)); // 获取NR禁用状态
- (CTNRStatus *)getNRStatus:(CTServiceDescriptor *)descriptor error:(NSError **)error API_AVAILABLE(ios(17.0)); // 获取NR禁用状态
-(BOOL)restoreToSystemBundles:(int *)outCode API_AVAILABLE(ios(15.0)); // 恢复到系统的Bundle 第一个参数是返回0
- (NSString *)copyCarrierBundleVersion:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取运营商配置文件版本号
-(void)copyCarrierBundleLocation:(id)arg1 completion:(/*^block*/id)arg2 ;
- (NSString *)copyCarrierBundleLocation:(CTXPCServiceSubscriptionContext *) context error:(NSError **)error; // 同步方法 获取Bundle所在目录
-(void)copyCarrierBundleVersion:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)context:(id)arg1 getCarrierBundleValue:(id)keyHierarchy completion:(/*^block*/id)arg3 ;
- (id)context:(CTXPCServiceSubscriptionContext *)context getCarrierBundleValue:(NSArray<NSString *> *)keyHierarchy error:(NSError **)error; // 使用key获取IPCC中的Value 错误的数据类型会导致基带服务崩溃
-(void)copyBundleIdentifier:(id)arg1 bundleType:(id)arg2 completion:(/*^block*/id)arg3 ;
-(id)copyBundleIdentifier:(id)arg1 bundleType:(id)arg2 error:(NSError **)error; // TODO
-(void)copyBundleLocation:(id)arg1 bundleType:(id)arg2 completion:(/*^block*/id)arg3 ;
-(id)copyBundleLocation:(id)arg1 bundleType:(id)arg2 error:(NSError **)error; // TODO
-(void)copyBundleVersion:(id)arg1 bundleType:(id)arg2 completion:(/*^block*/id)arg3 ;
-(id)copyBundleVersion:(id)arg1 bundleType:(id)arg2 error:(NSError **)error; // TODO
-(void)copyCarrierBookmarks:(CTXPCServiceSubscriptionContext *)context completion:(void (^)(NSDictionary *result, NSError *error))completion; // 获取运营商的书签
-(void)copyCarrierBundleValue:(id)arg1 key:(id)arg2 bundleType:(id)arg3 completion:(/*^block*/id)arg4 ;
-(id)copyCarrierBundleValue:(CTXPCServiceSubscriptionContext *)context key:(NSString *)key bundleType:(CTBundle *)bundleType error:(NSError **)error ; // 获取运营商配置文件的Value
-(void)copyCarrierBundleValue:(id)arg1 keyHierarchy:(id)arg2 bundleType:(id)arg3 completion:(/*^block*/id)arg4 ;
-(id)copyCarrierBundleValue:(CTXPCServiceSubscriptionContext *)context keyHierarchy:(NSArray<NSString *> *)keyHierarchy bundleType:(CTBundle *)bundleType error:(NSError **)error ; // 获取运营商配置文件的Value
-(id)copyCarrierBundleValueWithCountryBundleLookup:(id)arg1 keyHierarchy:(id)arg2 matchingInfo:(id)arg3 error:(id*)arg4 ;
-(void)copyCarrierBundleValueWithDefault:(id)arg1 key:(id)arg2 bundleType:(id)arg3 completion:(/*^block*/id)arg4 ;
-(id)copyCarrierBundleValueWithDefault:(id)arg1 key:(id)arg2 bundleType:(id)arg3 error:(id*)arg4 ;
-(void)copyCarrierBundleValueWithDefault:(id)arg1 keyHierarchy:(id)arg2 bundleType:(id)arg3 completion:(/*^block*/id)arg4 ;
-(id)copyCarrierBundleValueWithDefault:(id)arg1 keyHierarchy:(id)arg2 bundleType:(id)arg3 error:(id*)arg4 ;
-(void)copyCarrierBundleValues:(id)arg1 keyHierarchies:(id)arg2 defaultValues:(id)arg3 bundleType:(id)arg4 withFallbackBundleCheck:(BOOL)arg5 completion:(/*^block*/id)arg6 ;
-(id)copyCarrierBundleValues:(id)arg1 keyHierarchies:(id)arg2 defaultValues:(id)arg3 bundleType:(id)arg4 withFallbackBundleCheck:(BOOL)arg5 error:(id*)arg6 ;
-(void)copyCarrierBundleValues:(id)arg1 keys:(id)arg2 defaultValues:(id)arg3 bundleType:(id)arg4 withFallbackBundleCheck:(BOOL)arg5 completion:(/*^block*/id)arg6 ;
-(id)copyCarrierBundleValues:(id)arg1 keys:(id)arg2 defaultValues:(id)arg3 bundleType:(id)arg4 withFallbackBundleCheck:(BOOL)arg5 error:(id*)arg6 ;
-(NSNumber *)getAllowDevSignedCarrierBundlesFlag API_AVAILABLE(ios(16.0));
-(void)checkForUpdatedBundlesWithAutoInstall:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(id)getCountryBundleIdentifierForCountryCode:(id)arg1 error:(id*)arg2 ;
-(id)getCountryBundleLocationForBundleIdentifier:(id)arg1 error:(id*)arg2 ;
-(id)getCountryBundleLocationForMatchingInfo:(id)arg1 error:(id*)arg2 ;
-(void)getTetheringStatus:(/*^block*/id)arg1 API_AVAILABLE(ios(14.0));
-(CTTetheringStatus *)getTetheringStatusSync:(NSError **)error API_AVAILABLE(ios(15.0)); // 获取一些关于网络共享的信息 经过测试需要iOS 15.0+ limneos网站数据存在错误
-(void)getTetheringStatus:(/*^block*/id)arg1 connectionType:(int)arg2 API_AVAILABLE(ios(15.0));
-(id)getTetheringStatusSync:(NSError **)error connectionType:(int)connectionType API_AVAILABLE(ios(15.0));
-(id)setTetheringActive:(BOOL)active API_AVAILABLE(ios(14.0)); // 返回nil
-(void)setTetheringActive:(BOOL)arg1 completion:(/*^block*/id)arg2 API_AVAILABLE(ios(14.0));
-(BOOL)isTetheringEditingSupported:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error NS_SWIFT_NOTHROW; // 是否支持编辑网络共享
-(void)isTetheringEditingSupported:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)registerSetUpeSIMLaunchedEvent:(/*^block*/id)arg1 ;
//-(void)setMaxDataRate:(id)arg1 rate:(long long)arg2 completion:(/*^block*/id)arg3 ;
-(void)setMux:(CoreTelephonyClientMux *)arg1 ;
-(void)websheetInfoForPlan:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)SIMUnlockProcedureDidComplete;
-(id)context:(id)arg1 addPhoneServicesDevice:(id)arg2;
-(void)copyRejectCauseCode:(CTXPCServiceSubscriptionContext *)context completion:(/*^block*/id)arg2;
-(NSNumber *)getRejectCauseCode:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 被网络拒绝的原因代码
-(void)getRadioPersonality:(CTXPCServiceSubscriptionContext *)context completion:(/*^block*/id)arg2;
-(void)getStewieSupportWithCompletion:(/*^block*/id)arg1 ;
-(void)getTransferPlansWithCompletion:(/*^block*/id)arg1 ;
-(BOOL)isDedicatedBearerPresent:(id)arg1 error:(id*)arg2 ;
-(void)refreshSweetgumApps:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)submitSimSetupUsage:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)userEnteredMonthlyBudget:(id)arg1 error:(id*)arg2 ;
-(void)activateProximityTransfer:(unsigned long long)arg1 completion:(/*^block*/id)arg2 ;
-(void)activateStewieEmergencyTryOutWithCompletion:(/*^block*/id)arg1 ;
-(id)addDedicatedBearer:(id)arg1 error:(id*)arg2 ;
-(void)addLowLatencyFilter:(id)arg1 pdp:(int)arg2 queueSetId:(unsigned long long)arg3 uplink:(BOOL)arg4 completion:(/*^block*/id)arg5 ;
-(void)addPlanWith:(id)arg1 appName:(id)arg2 appType:(unsigned long long)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)addPlanWith:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)addPlanWith:(id)arg1 request:(id)arg2 appName:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)authenticate:(id)arg1 request:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)automaticallySelectNetwork:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)billingCycleEndDatesForLastPeriods:(unsigned long long)arg1 error:(id*)arg2 ;
-(void)cancelCellularPlanTransfer:(id)arg1 fromDevice:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)cancelCellularPlanTransfer:(id)arg1 fromDevice:(id)arg2 keepCache:(BOOL)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)carrierOneTimeCodeSendersWithCompletion:(/*^block*/id)arg1 ;
-(void)changePIN:(id)arg1 oldPin:(id)arg2 newPin:(id)arg3 completion:(/*^block*/id)arg4 ;
-(void)changePIN:(id)arg1 oldPin:(id)arg2 newPin:(id)arg3 error:(id*)arg4 ;
-(void)checkRadioBootHealth:(/*^block*/id)arg1 ; // 返回nil
-(void)clearUserEnteredBillingEndDayOfMonth:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)clearUserEnteredBillingEndDayOfMonth:(id)arg1 error:(id*)arg2 ;
-(void)clearUserEnteredMonthlyBudget:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)clearUserEnteredMonthlyBudget:(id)arg1 error:(id*)arg2 ;
-(void)clearUserEnteredMonthlyRoamingBudget:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)clearUserEnteredMonthlyRoamingBudget:(id)arg1 error:(id*)arg2 ;
-(void)compressWithStewieCodec:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)context:(id)arg1 addPhoneServicesDevice:(id)arg2 withCompletion:(/*^block*/id)arg3 ;
-(id)context:(id)arg1 canSetCapability:(id)arg2 allowed:(BOOL*)arg3 with:(id*)arg4 ;
-(void)context:(id)arg1 canSetCapability:(id)arg2 completion:(/*^block*/id)arg3 ;
-(id)context:(id)arg1 evaluateMobileSubscriberIdentity:(id)arg2 ;
-(void)context:(id)arg1 getCapability:(id)arg2 completion:(/*^block*/id)arg3 ;
-(id)context:(id)arg1 getCapability:(id)arg2 status:(BOOL*)arg3 with:(id*)arg4 ;
-(id)context:(id)arg1 getEncryptedIdentity:(id)arg2 error:(id*)arg3 ;
-(id)context:(id)arg1 getPhoneNumberSignature:(id*)arg2 ;
-(void)context:(id)arg1 getPhoneNumberSignatureWithCompletion:(/*^block*/id)arg2 ;
-(void)context:(id)arg1 getPseudoIdentityFor:(id)arg2 completion:(/*^block*/id)arg3 ;
-(id)context:(CTXPCServiceSubscriptionContext *)context getPseudoIdentityFor:(NSString *)identity error:(id*)error API_AVAILABLE(ios(13.0)); // TODO
- (NSDictionary<NSString *, id> *)context:(CTXPCServiceSubscriptionContext *)context getSystemCapabilities:(NSError **)error NS_SWIFT_NOTHROW; // 获取系统能力
-(void)context:(id)arg1 getSystemCapabilitiesWithCompletion:(/*^block*/id)arg2 ;
-(BOOL)context:(CTXPCServiceSubscriptionContext *)context isMandatoryDisabledVoLTE:(NSError **)error API_AVAILABLE(ios(14.0)) NS_SWIFT_NOTHROW; // 获取是否强制禁用VoLTE
-(void)context:(id)arg1 isProtectedIdentitySupported:(id)arg2 completion:(/*^block*/id)arg3 ;
-(BOOL)context:(id)arg1 isProtectedIdentitySupported:(id)arg2 error:(id*)arg3 ;
-(id)context:(id)arg1 recheckPhoneServicesAccountStatus:(id)arg2 ;
-(id)context:(id)arg1 removePhoneServicesDevice:(id)arg2 ;
-(void)context:(id)arg1 removePhoneServicesDevice:(id)arg2 withCompletion:(/*^block*/id)arg3 ;
-(id)context:(id)arg1 setCapability:(id)arg2 enabled:(BOOL)arg3 with:(id)arg4 ;
-(void)context:(id)arg1 setCapability:(id)arg2 enabled:(BOOL)arg3 with:(id)arg4 completion:(/*^block*/id)arg5 ;
-(void)context:(id)arg1 supportedIdentityProtectionFor:(id)arg2 completion:(/*^block*/id)arg3 ;
-(long long)context:(id)arg1 supportedIdentityProtectionFor:(id)arg2 error:(id*)arg3 ;
-(void)convertPhysicalToeSIMWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)copyAbbreviatedOperatorName:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)copyBandInfo:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)copyCellId:(CTXPCServiceSubscriptionContext *)context completion:(/*^block*/id)arg2; // 返回cellID本身
- (CTCellIdInfo *)copyPublicCellId:(CTServiceDescriptor *)descriptor error:(NSError **)error ; // 返回cellIdInfo 实例
-(void)copyCellInfo:(CTXPCServiceSubscriptionContext *)context completion:(void (^)(CTCellInfo * info, NSError * error))completion; // 获取连接信息
-(void)copyEmergencyMode:(/*^block*/id)arg1 ;
-(CTEmergencyModeResult *)copyEmergencyModeWithError:(NSError **)error API_AVAILABLE(ios(13.0)); // 获取设备紧急状态的实例
-(void)copyFirmwareUpdateInfo:(/*^block*/id)arg1 ;
-(void)copyIsDataAttached:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)copyIsInHomeCountry:(id)arg1 completion:(/*^block*/id)arg2 ;
- (NSNumber *)copyIsInHomeCountry:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error API_AVAILABLE(ios(13.0)); // 同步方法 判断当前卡是否在漫游
-(void)copyLastKnownMobileCountryCode:(id)arg1 completion:(/*^block*/id)arg2 API_AVAILABLE(ios(13.0));
- (NSString *)copyLastKnownMobileCountryCode:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error API_AVAILABLE(ios(13.0)); // 获取最后已知MCC
-(void)copyLastKnownMobileSubscriberCountryCode:(id)arg1 completion:(/*^block*/id)arg2 ;
- (NSString *)copyLastKnownMobileSubscriberCountryCode:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取最后已知MNC所属国家/地区的代码
//-(void)copyLocalizedOperatorName:(id)arg1 completion:(/*^block*/id)arg2;
- (void)copyLocalizedOperatorName:(CTXPCServiceSubscriptionContext *)context completion:(void (^)(id result))completion;
-(void)copyLocationAreaCode:(CTXPCServiceSubscriptionContext *)context completion:(void (^)(NSNumber * lac, NSError *error))completion; // 获取LAC
-(id)copyMccOrPlmnsListForIso3CountryCode:(NSString *)Iso3CountryCode error:(id*)error ; // TODO
-(id)copyMobileSubscriberIso3CountryCode:(id)arg1 MNC:(id)arg2 error:(id*)arg3 ;
-(id)copyMobileSubscriberIsoCountryCode:(NSString *)arg1 error:(NSError **)arg2 ;
-(id)copyMobileSubscriberIsoSubregionCode:(id)arg1 MNC:(id)arg2 error:(id*)arg3 ;
-(void)copyNetworkList:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)copyNetworkSelection:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)copyNetworkSelectionInfo:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)copyNetworkSelectionMode:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)copyNetworkSelectionState:(id)arg1 completion:(/*^block*/id)arg2 ; // iOS 26已移除
-(void)copyWirelessTechnology:(id)context completion:(/*^block*/id)arg2 ; // 返回LTE这种
-(void)copyRegistrationAgentStatus:(CTXPCServiceSubscriptionContext *)context completion:(/*^block*/id)arg2 ; // 三个闭包参数 返回nil
-(void*)createAssertionForConnectionType:(int)arg1 allocator:(CFAllocatorRef)arg2 error:(id*)arg3 onReAssertError:(/*^block*/id)arg4 ;
-(void)createEncryptedIdentity:(id)arg1 identity:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)dataUsageForLastPeriods:(unsigned long long)arg1 completion:(/*^block*/id)arg2 ;
-(void)dataUsageForLastPeriodsOnActivePairedDevice:(unsigned long long)arg1 completion:(/*^block*/id)arg2 ;
-(void)deleteHiddenSims:(/*^block*/id)arg1 ;
-(void)deleteLowLatencyFilter:(id)arg1 pdp:(int)arg2 queueSetId:(unsigned long long)arg3 uplink:(BOOL)arg4 completion:(/*^block*/id)arg5 ;
//-(id)deletePersonalWallet:(id)arg1 ; // 删除eSIM全部数据
//-(void)deletePersonalWallet:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)deleteTransferPlansForImei:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)deleteZone:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)disableRejectedIccid:(/*^block*/id)arg1 API_AVAILABLE(ios(16.0));
-(void)dispatchBlockToClientAsync:(/*^block*/id)arg1 ;
-(void)encryptDataForPlan:(id)arg1 data:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)encryptDataWithCarrierIdentifiers:(id)arg1 mnc:(id)arg2 gid1:(id)arg3 gid2:(id)arg4 data:(id)arg5 completion:(/*^block*/id)arg6 ;
-(id)endPlanTransferForEndPoint:(unsigned long long)arg1 ;
-(id)enterLoopBackMode; // 非RC固件 不支持
-(void)evaluateMobileSubscriberIdentity:(id)arg1 identity:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)exitStewieWithContext:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void*)fDataAssertion;
-(id)fetchBasebandTicket:(BOOL)arg1 withError:(NSError **)error API_AVAILABLE(ios(16.0)); // TODO
-(id)fetchCallBarringValue:(id)arg1 facility:(int)arg2 callClass:(int)arg3 password:(id)arg4 ;
-(void)fetchCallBarringValue:(id)arg1 facility:(int)arg2 callClass:(int)arg3 password:(id)arg4 completion:(/*^block*/id)arg5 ;
-(id)fetchCallForwardingValue:(id)arg1 reason:(int)arg2 callClass:(int)arg3 ;
-(void)fetchCallForwardingValue:(id)arg1 reason:(int)arg2 callClass:(int)arg3 completion:(/*^block*/id)arg4 ;
-(id)fetchCallWaitingValue:(id)arg1 callClass:(int)arg2 ;
-(void)fetchCallWaitingValue:(id)arg1 callClass:(int)arg2 completion:(/*^block*/id)arg3 ;
-(id)fetchCallingLineIdRestrictionValue:(id)arg1 ; // 返回nil
-(void)fetchCallingLineIdRestrictionValue:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)fetchCallingLinePresentationValue:(id)arg1 ; // 返回nil
-(void)fetchCallingLinePresentationValue:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)fetchConnectedLineIdRestrictionValue:(id)arg1 ; // 返回nil
-(void)fetchConnectedLineIdRestrictionValue:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)fetchConnectedLinePresentationValue:(id)arg1 ;
-(void)fetchConnectedLinePresentationValue:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)fetchNetworkList:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)forceRollAllTransportKeys;
-(void)generateAuthenticationInfoUsingSim:(id)arg1 authParams:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)get2GSwitchEnabled:(/*^block*/id)arg1 API_AVAILABLE(ios(17.0));
-(BOOL)get2GSwitchEnabledSync:(NSError **)error API_AVAILABLE(ios(17.0)) NS_SWIFT_NOTHROW;
-(void)get2GUserPreference:(/*^block*/id)arg1 API_AVAILABLE(ios(17.0));
-(BOOL)get2GUserPreferenceSync:(NSError **)error API_AVAILABLE(ios(17.0)) NS_SWIFT_NOTHROW;
-(void)set2GUserPreference:(BOOL)arg1 completion:(/*^block*/id)arg2 API_AVAILABLE(ios(17.0));
-(void)getAnbrActivationState:(id)arg1 completion:(/*^block*/id)arg2 API_AVAILABLE(ios(16.0));
-(id)getBasebandRadioFrequencyFrontEndScanData:(NSError **)error ; // 需要internal权限
-(CTCallCapabilities *)getCallCapabilities:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error ; // 是否支持WI-FI Calling
-(void)getCallCapabilities:(CTXPCServiceSubscriptionContext *)context completion:(/*^block*/id)arg2;
-(void)getCameraScanInfoForCardData:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)getCarrierSetupWithCompletion:(/*^block*/id)arg1 ;
-(CTCellularUsageWorkspaceInfo *)getCellularUsageWorkspaceInfo:(NSError **)error API_AVAILABLE(ios(17.0));
-(id)context:(id)arg1 getAttachApnSettings:(id*)arg2 ; // 返回nil
-(id)context:(id)arg1 modifyAttachApnSettings:(id)arg2 ;
-(void)context:(id)arg1 modifyAttachApnSettings:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)getConfiguredApns:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)isAttachApnSettingAllowed:(id)arg1 completion:(/*^block*/id)arg2 ;
-(BOOL)isAttachApnSettingAllowed:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error NS_SWIFT_NOTHROW; // 是否允许附加APN
-(NSArray<NSDictionary *> *)getConfiguredApns:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error ; // 获取卡槽APN
-(id)resetAPNSettings; // 重设 APN
-(void)resetAPNSettings:(/*^block*/id)arg1 ;
-(void)getUIConfiguredApns:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)getUIConfiguredApns:(id)arg1 error:(id*)arg2 ; // 返回nil
-(void)setUIConfiguredApns:(id)arg1 apns:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)resetUIConfiguredApns:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)getConnectionAssistantConfig:(/*^block*/id)arg1 API_AVAILABLE(ios(16.0));
-(id)getConnectionAssistantConfigWithError:(id*)arg1 API_AVAILABLE(ios(16.0)); // TODO 返回 错误45
-(void)getConnectionAssistantServicePlot:(/*^block*/id)arg1 ;
-(id)getConnectionAssistantServicePlotWithError:(id*)arg1 API_AVAILABLE(ios(16.0)); // 需要 connection-assistant 权利 返回 错误 45
-(void)getConnectionAssistantState:(/*^block*/id)arg1 ;
-(id)getConnectionAssistantStateWithError:(id*)arg1 ; // TODO 返回 错误45
-(void)getConnectionAvailability:(id)arg1 connectionType:(int)arg2 completion:(/*^block*/id)arg3 ;
-(id)getConnectionAvailability:(id)arg1 connectionType:(int)arg2 error:(id*)arg3 ;
-(void)getConnectionState:(id)arg1 connectionType:(int)arg2 completion:(/*^block*/id)arg3 ;
-(id)getConnectionState:(id)arg1 connectionType:(int)arg2 error:(id*)arg3 ;
-(NSString *)getCurrentRat:(CTServiceDescriptor *)descriptor error:(NSError **)error; // 返回当前用的网络制式
-(void)getDataStatus:(id)arg1 completion:(/*^block*/id)arg2 ;
-(CTDataStatus *)getDataStatus:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 通过context 获取蜂窝网络的一些参数
-(CTDataStatus *)getInternetDataStatusSync:(NSError **)error API_AVAILABLE(ios(13.0)); // 直接获取蜂窝网络的一些参数
-(void)getInternetDataStatus:(/*^block*/id)arg1 ;
-(void)getDataStatusBasic:(CTXPCServiceSubscriptionContext *)context completion:(/*^block*/id)arg2 API_AVAILABLE(ios(15.4));
-(CTDataStatusBasic *)getDataStatusBasic:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error API_AVAILABLE(ios(15.4)); // 获取数据状态的基本信息 同步方法
-(void)getEOSFirmwareUpdateInfo:(/*^block*/id)arg1 ;
-(void)getEmergencyTextNumbers:(id)arg1 completion:(/*^block*/id)arg2 ;
-(NSArray *)getEmergencyTextNumbers:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error API_AVAILABLE(ios(13.0)); // 获取紧急呼叫电话号码列表
-(id)getEncryptionStatus:(CTServiceDescriptor *)descriptor error:(id*)error ; // TODO 返回拒绝状态错误
-(void)getEnhancedVoiceLinkQualityMetric:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)getEosStatus:(/*^block*/id)arg1 API_AVAILABLE(ios(16.0)); // 需要额外权利
-(id)getEvolvedSubscriptionLabelID:(NSString *)labelID error:(NSError **)error API_AVAILABLE(ios(16.0)); // 第一个参数不是context TODO
-(void)getEvolvedSubscriptionLabelID:(NSString *)labelID withCallback:(/*^block*/id)arg2 API_AVAILABLE(ios(16.0));
-(unsigned long long)getGSMAUIControlSetting:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error API_AVAILABLE(ios(15.0)); // TODO 暂时不知道做什么的 返回0
-(void)getInternationalDataAccess:(id)arg1 completion:(/*^block*/id)arg2 ; // 返回nil
-(void)getInternationalDataAccessStatus:(/*^block*/id)arg1 ; // 返回nil
-(BOOL)getInternationalDataAccessStatusSync:(NSError **)error NS_SWIFT_NOTHROW; // 设备当前是否开启数据漫游
-(BOOL)getInternationalDataAccessSync:(CTServiceDescriptor *)descriptor error:(NSError **)error API_AVAILABLE(ios(13.4)) NS_SWIFT_NOTHROW; // 卡槽是的卡否开启数据漫游
-(void)getInternetConnectionAvailability:(/*^block*/id)arg1 ; // 是否启用蜂窝数据 异步方法
- (CTDataConnectionAvailabilityStatus *)getInternetConnectionAvailabilitySync:(NSError **)error API_AVAILABLE(ios(13.0)); // 是否启用蜂窝数据 同步方法
-(void)getInternetConnectionState:(/*^block*/id)arg1 ;
-(CTDataConnectionStatus *)getInternetConnectionStateSync:(NSError **)error API_AVAILABLE(ios(13.0)); // 分析QoS很有用
-(void)getInternetDataStatusBasic:(/*^block*/id)arg1 API_AVAILABLE(ios(16.0));
-(CTDataStatusBasic *)getInternetDataStatusBasicSync:(NSError **)error API_AVAILABLE(ios(16.0));
-(id)setInternetActive:(BOOL)arg1 ;
-(void)setInternetActive:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(id)getLastKnownSimDeactivationInfoFor:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error API_AVAILABLE(ios(15.0)); // 返回设备未配置 错误 6
-(id)getListOfPresentDedicatedBearers; //返回一个空对象
-(void)getLowLatencyFilters:(int)arg1 queueSetId:(unsigned long long)arg2 completion:(/*^block*/id)arg3 ;
-(void)getMaxDataRate:(CTXPCServiceSubscriptionContext *)context completion:(/*^block*/id)arg2;
-(long long)getMaxDataRate:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取当前的网络类型
-(void)copyMobileEquipmentInfo:(/*^block*/id)arg1 ;
-(CTMobileEquipmentInfoList *)getMobileEquipmentInfo:(NSError **)error; // 获取设备基本信息 IMEI EID MEID这些
-(CTMobileEquipmentInfo *)getMobileEquipmentInfoFor:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取卡槽使用的设备基本信息 IMEI EID MEID这些
-(void)getMobileSubscriberHomeCountryList:(id)arg1 completion:(/*^block*/id)arg2 ;
-(NSArray<NSString *> *)getMobileSubscriberHomeCountryList:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取SIM卡的国家/地区ISO代码列表
-(unsigned)getNATTKeepAliveOverCell:(NSError **)error API_AVAILABLE(ios(13.0)); // NAT保活时间
-(unsigned int)getNATTKeepAliveOverCell:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error ; // 最大NAT保活时间
-(unsigned int)private_getNATTKeepAliveOverCell:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error ;
-(unsigned int)getNATTKeepAliveOverCellForPreferredDataContext:(NSError **)error ;
-(void)getNATTKeepAliveOverCell:(CTXPCServiceSubscriptionContext *)context completion:(/*^block*/id)arg2 ;
-(void)getOperatorMultiPartyCallCountMaximum:(id)arg1 completion:(/*^block*/id)arg2;
- (NSNumber *)getOperatorMultiPartyCallCountMaximum:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error ; // 获取多方通话的最大人数
-(void)getPNRContext:(id)arg1 completion:(/*^block*/id)arg2 ;
- (CTPNRContextInfo *)getPNRContext:(CTXPCServiceSubscriptionContext *)context outError:(NSError **)error; // 获取PNR实例
-(void)isPNRSupported:(id)arg1 completion:(/*^block*/id)arg2 ;
- (BOOL)isPNRSupported:(CTXPCServiceSubscriptionContext *)context outError:(NSError **)error NS_SWIFT_NOTHROW; // 是否支持PNR
-(void)issuePNRRequest:(id)arg1 pnrReqType:(id)arg2 completion:(/*^block*/id)arg3 ;
-(BOOL)isPhoneNumberCredentialValid:(CTXPCServiceSubscriptionContext *)context outError:(NSError **)error NS_SWIFT_NOTHROW; // PNR相关
- (CTPhoneNumberInfo *)getPhoneNumber:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error API_AVAILABLE(ios(13.0)); // 获取电话号码实例
-(void)getPhoneNumberWithCompletion:(id)arg1 completion:(/*^block*/id)arg2 ;
- (NSDictionary<NSString *, id> *)getPhoneServicesDeviceInfo:(id*)error ; // TODO 共享账户相关信息
-(void)getPhoneServicesDeviceInfoWithCompletion:(/*^block*/id)arg1 ;
- (id)getPhoneServicesDeviceList:(NSError **)error; // TODO 共享账户相关内容
-(void)getPhoneServicesDeviceListWithCompletion:(/*^block*/id)arg1 ;
// SIM卡通讯录相关的API
-(int)getPhonebookEntryCount:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error ; // 获取SIM卡中存储的通讯录数量 已废弃 返回0
//-(void)getPhonebookEntryCountWithCompletion:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)getPhonebookEntryCountWithCompletion:(CTXPCServiceSubscriptionContext *)context completion:(void (^)(NSNumber *count))completion;
-(CTPhoneBookEntry *)getPhonebookEntry:(CTXPCServiceSubscriptionContext *)context atIndex:(int)index error:(NSError **)error ; // 获取SIM卡中通讯录的联系人 就算SIM卡有联系人也不支持 获取不到
-(void)getPhonebookEntryWithCompletion:(id)arg1 atIndex:(int)arg2 completion:(/*^block*/id)arg3 ;
-(void)selectPhonebook:(id)arg1 forPhonebookName:(int)arg2 withPassword:(id)arg3 completion:(/*^block*/id)arg4 ;
-(void)savePhonebookEntry:(id)arg1 atIndex:(int)index withContactName:(id)contactName contactNumber:(id)contactNumber completion:(/*^block*/id)arg5 ;
- (void)fetchPhonebook:(CTXPCServiceSubscriptionContext *)context completion:(void (^)(NSArray *entries, NSError *error))completion;
-(void)getPlanTransferCredentials:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)getPrefForKey:(id)arg1 heirarchy:(id)arg2 storage:(id)arg3 completion:(/*^block*/id)arg4 ;
-(id)getPrefForKey:(id)arg1 heirarchy:(id)arg2 storage:(id)arg3 error:(id*)arg4 ;
- (CTPrivacyProxyState)getPrivacyProxyState:(CTServiceDescriptor *)descriptor error:(NSError **)error API_AVAILABLE(ios(15.0)); // 获取iCloud Private Relay
-(void)getProximityTransportSession:(unsigned long long)arg1 remoteDeviceInfo:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)getPublicDataBearer:(/*^block*/id)arg1 API_AVAILABLE(ios(15.0));
-(int)getPublicDataBearerSync:(NSError **)error API_AVAILABLE(ios(15.0)); // 获取 DataBearer
-(void)getPublicNrFrequencyRange:(/*^block*/id)arg1 ; // iOS 18已移除此方法
-(unsigned)getPublicNrFrequencyRangeSync:(NSError **)error; // 获取NR频率范围 iOS 18已移除此方法
-(id)getQoSLinkCharacteristics:(id*)arg1 API_AVAILABLE(ios(15.0)); // 返回nil
-(id)getRadioPersonality:(NSString *)arg1 error:(NSError **)error ;
- (void)getRatSelection:(CTXPCServiceSubscriptionContext *)context completion:(void (^)(NSString *currentSelection, NSString *preferredSelection, NSError *error))completion; // 获取网络类型选择的实例 异步方法 低版本兼容方案
-(CTRatSelection *)getRatSelectionMask:(CTServiceDescriptor *)descriptor error:(NSError **)error API_AVAILABLE(ios(14.0)); // 获取网络类型选择的实例 同步方法 需要14.0+
-(void)setRatSelection:(CTXPCServiceSubscriptionContext *)context selection:(NSString *)selection preferred:(NSString *)preferred completion:(void (^)(NSError *error))completion NS_SWIFT_NOTHROW; // 低版本的兼容方法
-(id)setRatSelectionMask:(CTServiceDescriptor *)descriptor selection:(NSString *)selection preferred:(NSString *)preferred API_AVAILABLE(ios(15.0)); // 可以锁定网络类型
- (NSString *)getSIMStatus:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取SIM卡状态
-(void)getSIMStatus:(CTXPCServiceSubscriptionContext *)context completion:(/*^block*/id)arg2 ;
- (NSNumber *)fetchSIMLockValue:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error ; // 获取SIM卡是否已经被PIN锁住
-(void)fetchSIMLockValue:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)getRemainingPINAttemptCount:(id)arg1 completion:(/*^block*/id)arg2 ;
- (NSNumber *)getRemainingPINAttemptCount:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取SIM卡剩余可尝试PIN次数
-(void)getRemainingPUKAttemptCount:(id)arg1 completion:(/*^block*/id)arg2 ;
- (NSNumber *)getRemainingPUKAttemptCount:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取SIM卡剩余可尝试PUK次数
-(id)getRemoteDeviceForTransferWithEID:(id)arg1 error:(id*)arg2 ;
-(id)getRemoteDeviceOfType:(unsigned long long)arg1 withEID:(id)arg2 error:(id*)arg3 ;
-(void)getRemoteDevices:(/*^block*/id)arg1 ;
-(id)getRemoteDevicesForTransferOrError:(NSError **)error API_AVAILABLE(ios(14.0)); // 返回错误1
-(id)getRemoteDevicesOfType:(unsigned long long)arg1 error:(id*)arg2 ;
-(void)getRemotePlanManageAccountInfoFor:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)fetchRoadsideProvidersWithContext:(id)arg1 completion:(/*^block*/id)arg2 API_AVAILABLE(ios(17.0)); // 2个闭包参数 返回nil
-(id)fetchRoadsideProvidersWithContext:(id)arg1 error:(id*)arg2 API_AVAILABLE(ios(17.0));
-(id)getResumableRoadsideProvider:(id*)arg1 API_AVAILABLE(ios(17.0)); // 返回不支持
-(void)getResumableRoadsideProviderWithCompletion:(/*^block*/id)arg1 API_AVAILABLE(ios(17.0));
-(void)selectRoadsideProviderWithContext:(id)arg1 completion:(/*^block*/id)arg2 API_AVAILABLE(ios(17.0));
-(id)selectRoadsideProviderWithContext:(id)arg1 error:(id*)arg2 API_AVAILABLE(ios(17.0)); // 第一个参数是 CTSelectRoadsideProviderContext
-(void)getIMSRegistrationStatus:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)copyRegistrationIMSTransportInfo:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)getSignalStrengthInfo:(id)arg1 completion:(/*^block*/id)arg2 ;
-(CTSignalStrengthInfo *)getSignalStrengthInfo:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取信号格信息
-(CTSignalStrengthInfo *)getPublicSignalStrength:(CTServiceDescriptor *)descriptor error:(NSError **)error; // 获取数据卡描述的信号信息
-(void)getSignalStrengthMeasurements:(CTServiceDescriptor *)descriptor completion:(/*^block*/id)arg2 ;
-(CTSignalStrengthMeasurements *)getSignalStrengthMeasurements:(CTServiceDescriptor *)descriptor error:(NSError **)error API_AVAILABLE(ios(13.0)); // 获取信号详细信息
-(CTSimHardwareInfo *)getSimHardwareInfo:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error API_AVAILABLE(ios(15.0)); // 获取SIM卡的信息
-(id)getSliceTrafficDescriptors:(id*)arg1 API_AVAILABLE(ios(17.0)); // 获取5G切片的数据 需要iOS 17.0+ 返回CTTrafficDescriptorsContainer
-(id)getSliceTrafficDescriptorsInfo:(id)arg1 connectionType:(int)arg2 error:(id*)arg3 API_AVAILABLE(ios(17.0));
-(void)getSmsReadyState:(CTXPCServiceSubscriptionContext *)context completion:(/*^block*/id)arg2;
-(NSNumber *)getSmsReadyState:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取短信是否就绪
-(void)getSmscAddress:(CTXPCServiceSubscriptionContext *)context completion:(/*^block*/id)arg2 ;
-(NSString *)getSmscAddress:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取短信中心号码
-(id)getStewieSupport:(NSError **)error API_AVAILABLE(ios(16.0)); // 返回不支持
-(void)getSweetgumApps:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)getSweetgumCapabilities:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)getSweetgumDataPlanMetrics:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)getSweetgumPlans:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)getSweetgumUsage:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)getSweetgumUserConsentInfo:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)getTransferPlanListWithCompletion:(/*^block*/id)arg1 ;
-(void)getTransferType:(id)arg1 remoteEid:(id)arg2 completion:(/*^block*/id)arg3 ;
-(id)getTransportKeysToUpdate:(id*)arg1 ; // 返回不支持
-(void)getTransportKeysToUpdateWithCompletion:(/*^block*/id)arg1 ;
-(id)getUserAuthToken:(CTServiceDescriptor *)descriptor error:(id*)error ; // 需要 public-subscriber-info 权利 
-(void)getVoiceLinkQualityMetric:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)getVoicemailInfo:(id)arg1 completion:(/*^block*/id)arg2 ; // 返回nil
-(void)getWiFiCallingSettingPreferences:(id)arg1 key:(id)arg2 completion:(/*^block*/id)arg3 ;
-(id)getWiFiCallingSettingPreferences:(id)arg1 key:(id)arg2 error:(id*)arg3 ;
-(BOOL)hasDedicatedBearerSupport API_AVAILABLE(ios(15.0)); // 设备是否支持专用承载
-(void)hiddenTransferPlans:(/*^block*/id)arg1 ;
-(void)hideTransferCellularPlan:(id)arg1 fromDevice:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)hideTransferPlan:(id)arg1 fromDevice:(id)arg2 completion:(/*^block*/id)arg3 ;
//-(id)initWithQueue:(dispatch_queue_sRef)arg1 multiplexer:(id)arg2 ;
-(void)installPendingPlan:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)installPendingPlanList:(id)arg1 completion:(/*^block*/id)arg2 ;
-(BOOL)interfaceCostExpensive:(CTServiceDescriptor *)descriptor error:(NSError **)error API_AVAILABLE(ios(14.0)) NS_SWIFT_NOTHROW; // 当前网络是否是昂贵的
-(id)setOverriddenInterfaceCostInexpensive:(BOOL)arg1;
-(BOOL)overriddenInterfaceCostInexpensive:(id*)arg1 ;
-(id)setInterfaceCost:(id)arg1 expensive:(BOOL)arg2 ;
-(void)invalidateCrossPlatformPlanTransfer:(/*^block*/id)arg1 ;
-(void)invalidateProximityTransfer:(unsigned long long)arg1 force:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)isAnyPlanOfTransferCapability:(unsigned long long)arg1 availableForThisDeviceWithCompletion:(/*^block*/id)arg2 ;
-(BOOL)isAnyPlanTransferableFromThisDeviceOrError:(NSError **)error API_AVAILABLE(ios(13.0)) NS_SWIFT_NOTHROW;
-(void)getAllEmergencyNumbers:(/*^block*/id)arg1;
-(NSArray<NSString *> *)getAllEmergencyNumbersWithError:(NSError **)error API_AVAILABLE(ios(16.0)); // 获取紧急呼叫号码列表
-(void)isEmergencyNumber:(id)arg1 number:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)isEmergencyNumberWithWhitelistIncluded:(id)arg1 number:(id)arg2 completion:(/*^block*/id)arg3 ;
-(BOOL)isEmergencyNumberWithWhitelistIncluded:(id)arg1 number:(id)arg2 error:(id*)arg3 ;
-(BOOL)isEmergencyNumber:(CTXPCServiceSubscriptionContext *)context number:(id)arg2 error:(id*)error ;
-(long long)isEsimFor:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error; // 获取卡槽中的卡类型
-(NSNumber *)getDataMode:(CTServiceDescriptor *)descriptor error:(NSError **)error ; // 获取当前的蜂窝网络类型的索引 不是设置低数据模式的数据模式 返回数字
-(BOOL)isHighDataModeSupported:(CTServiceDescriptor *)descriptor error:(NSError **)error API_AVAILABLE(ios(14.0)) NS_SWIFT_NOTHROW; // 是否支持高数据模式 自动5G 就是5G允许更多数据
-(BOOL)smartDataMode:(CTServiceDescriptor *)descriptor error:(NSError **)error API_AVAILABLE(ios(14.0)) NS_SWIFT_NOTHROW; // 启用自动5G
-(id)setSmartDataMode:(id)arg1 enable:(BOOL)arg2 API_AVAILABLE(ios(14.0));
-(BOOL)lowDataMode:(CTServiceDescriptor *)descriptor error:(NSError **)error API_AVAILABLE(ios(14.0)) NS_SWIFT_NOTHROW; // 是否是低数据模式
-(id)setLowDataMode:(id)arg1 enable:(BOOL)arg2 API_AVAILABLE(ios(14.0));
-(BOOL)saveDataMode:(CTServiceDescriptor *)descriptor error:(NSError **)error API_AVAILABLE(ios(13.0)) NS_SWIFT_NOTHROW; // 获取低数据模式 iOS 13开始有的接口 跟lowDataMode一样
-(id)setSaveDataMode:(CTXPCServiceSubscriptionContext *) context enable:(BOOL)enable API_AVAILABLE(ios(13.0));
-(void)isNetworkReselectionNeeded:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)isNetworkSelectionMenuAvailable:(id)arg1 completion:(/*^block*/id)arg2 ;
-(NSNumber *)isNetworkSelectionMenuAvailable:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error ; // 是否支持手动选网
-(BOOL)isPrivateNetworkEvaluationNeeded:(NSError **)error API_AVAILABLE(ios(17.0));
-(void)isPrivateNetworkPreferredOverWifi:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)isPrivateNetworkSIM:(id)arg1 completion:(/*^block*/id)arg2 API_AVAILABLE(ios(16.0));
-(BOOL)isPrivateNetworkSIM:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error API_AVAILABLE(ios(16.0)) NS_SWIFT_NOTHROW; // 获取当前的SIM卡是否为私有网络的SIM卡
-(id)isSimMatching:(id)arg1 carrierDescriptors:(id)arg2 error:(id*)arg3 ;
-(void)isUnconditionalCallForwardingActive:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)isVinylTapeSupportedWithError:(id*)error ; // TODO 需要额外权利
-(void)isVinylTestModeEnabledWithCompletion:(/*^block*/id)arg1 ;
-(NSArray<NSString *> *)listPersonalWallets:(NSError **)error; // 获取设备内存储的SIM卡ICCID列表
-(id)loadGSMASettings:(CTXPCServiceSubscriptionContext *)context state:(BOOL)state API_AVAILABLE(ios(15.0)); // 返回nil
-(NSNumber *)needToLaunchSetUpeSIM:(NSError **)error API_AVAILABLE(ios(16.0)); // 是否需要去设置eSIM
-(void)performNetworkAccessFlowIfAllowed:(id)arg1 ignoreForeground:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)plansPendingCrossPlatformTransferWithCompletion:(/*^block*/id)arg1 ;
-(void)plansPendingInstallWithCompletion:(/*^block*/id)arg1 ;
-(void)prepareCrossPlatformPlanTransfer:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)private_getActiveConnections:(id)arg1 error:(id*)arg2 ;
-(id)private_getConnectionAvailability:(id)arg1 connectionType:(int)arg2 error:(id*)arg3 ;
-(id)private_getConnectionState:(id)arg1 connectionType:(int)arg2 error:(id*)arg3 ;
-(id)private_getDataStatus:(id)arg1 error:(id*)arg2 ;
-(id)private_getSliceTrafficDescriptors:(id*)arg1 ;
-(id)private_getSliceTrafficDescriptorsInfo:(id)arg1 connectionType:(int)arg2 error:(id*)arg3 ;
-(id)private_setPacketContextActiveByServiceType:(id)arg1 connectionType:(int)arg2 active:(BOOL)arg3 ;
-(void)promptForSIMUnlock:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)purchaseSweetgumPlan:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)queryAnbrBitrate:(id)arg1 bitrate:(id)arg2 direction:(int)arg3 completion:(/*^block*/id)arg4 ;
-(void)refreshCellMonitor:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)refreshSweetgumAll:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)refreshSweetgumPlans:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)refreshSweetgumUsage:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)refreshUserAuthToken:(id)arg1 error:(id*)arg2 ;
//-(void)registerBlockForInvalidationNotification:(_CTAssertionType*)arg1 callback:(/*^block*/id)arg2 ;
-(CTReliableNetworkFallbackState)reliableNetworkFallback:(CTServiceDescriptor *)descriptor error:(id*)error API_AVAILABLE(ios(14.0)); // TODO
-(void)remotePlanSignupInfoFor:(id)arg1 userConsent:(long long)arg2 completion:(/*^block*/id)arg3 ;
-(id)removeAllDedicatedBearers;
-(id)removeDedicatedBearer:(id)arg1 ;
-(BOOL)removeGeofenceProfile;
-(id)renamePersonalWallet:(id)arg1 to:(id)arg2 ;
-(id)reportStewieConnectionAssistantEvent:(id)arg1 ;
-(void)reportStewieConnectionAssistantEvent:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)reportStewieDeviceOrientation:(id)arg1 ;
-(void)reportStewieDeviceOrientation:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)requestQoSLinkCharacteristics API_AVAILABLE(ios(15.0)); // 返回不支持
-(void)requestStewieWithContext:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)resetProximityTransportExtension:(/*^block*/id)arg1 ;
-(void)retrieveAppListURLWithCompletion:(/*^block*/id)arg1 API_AVAILABLE(ios(17.0));
-(id)saveCallBarringValue:(id)arg1 facility:(int)arg2 callClass:(int)arg3 enabled:(BOOL)arg4 password:(id)arg5 ;
-(void)saveCallBarringValue:(id)arg1 facility:(int)arg2 callClass:(int)arg3 enabled:(BOOL)arg4 password:(id)arg5 completion:(/*^block*/id)arg6 ;
-(id)saveCallForwardingValue:(id)arg1 value:(id)arg2 ;
-(void)saveCallForwardingValue:(id)arg1 value:(id)arg2 completion:(/*^block*/id)arg3 ;
-(id)saveCallWaitingValue:(id)arg1 callClass:(int)arg2 enabled:(BOOL)arg3 ;
-(void)saveCallWaitingValue:(id)arg1 callClass:(int)arg2 enabled:(BOOL)arg3 completion:(/*^block*/id)arg4 ;
-(id)saveCallingLineIdRestrictionValue:(id)arg1 restrictionValue:(int)arg2 ;
-(void)saveCallingLineIdRestrictionValue:(id)arg1 restrictionValue:(int)arg2 completion:(/*^block*/id)arg3 ;
-(void)saveSIMLockValue:(id)arg1 enabled:(BOOL)arg2 pin:(id)arg3 completion:(/*^block*/id)arg4 ;
-(void)saveSIMLockValue:(id)arg1 enabled:(BOOL)arg2 pin:(id)arg3 error:(id*)arg4 ;
-(void)selectNetwork:(id)arg1 network:(id)arg2 completion:(/*^block*/id)arg3 ;
-(id)sendDeadPeerDetection;
-(void)sendDeadPeerDetection:(/*^block*/id)arg1 ;
-(id)selectSIMToolkitListItem:(id)arg1 session:(id)arg2 response:(id)arg3 index:(id)arg4 ;
-(id)sendSIMToolkitBooleanResponse:(id)arg1 session:(id)arg2 response:(id)arg3 yesNo:(BOOL)arg4 ;
-(id)sendSIMToolkitDisplayReady:(id)arg1 ;
-(id)sendSIMToolkitResponse:(id)arg1 session:(id)arg2 response:(id)arg3 ;
-(id)sendSIMToolkitStringResponse:(id)arg1 session:(id)arg2 response:(id)arg3 string:(id)arg4 ;
-(id)sendSIMToolkitUSSDResponse:(id)arg1 response:(id)arg2 ;
-(id)sendSIMToolkitUserActivity:(id)arg1 ;
-(id)selectSIMToolkitMenuItem:(id)arg1 index:(id)arg2 ;
-(id)getSIMToolkitListItems:(CTXPCServiceSubscriptionContext *)context items:(id*)arg2 ;
-(id)getSIMToolkitMenu:(id)arg1 menu:(id*)arg2 ;
-(id)getSIMToolkitUSSDString:(id)arg1 ussdString:(id*)arg2 needRsp:(BOOL*)arg3 ;
-(id)cancelSIMToolkitUSSDSession:(CTXPCServiceSubscriptionContext *)context;
-(void)sendTaggedInfo:(id)arg1 type:(unsigned long long)arg2 payload:(id)arg3 completion:(/*^block*/id)arg4 ;
-(void)setActiveBandInfo:(id)arg1 bands:(id)arg2 error:(id*)arg3 ;
-(void)setActiveUserDataSelection:(CTXPCServiceSubscriptionContext *)context completion:(/*^block*/id)completion;
- (void)setActiveUserDataSelection:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error;
-(id)setApplicationCategory:(id)arg1 API_AVAILABLE(ios(17.0));
-(void)setBandInfo:(id)arg1 bands:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)setCoalescing:(BOOL)arg1 udp:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)setDefaultVoice:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)setDefaultVoice:(id)arg1 error:(id*)arg2 ; // 设置默认语音号码
-(void)setEosStatus:(id)arg1 assertionState:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)setFDataAssertion:(void*)arg1 ;
-(void)setInternationalDataAccess:(id)arg1 status:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(id)setInternationalDataAccessStatus:(BOOL)arg1 ;
-(void)setInternationalDataAccessStatus:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(id)setInternationalDataAccessSync:(id)arg1 status:(BOOL)arg2 ;
-(void)getLocalPolicies:(id)arg1 completion:(/*^block*/id)arg2 ;
//-(id)getLocalPolicies:(id)arg1 error:(id*)error API_AVAILABLE(ios(15.0)); // 参数不对 只接受 NSArray这些 返回nil
-(id)getLocalPolicies:(NSArray <NSString *> *)policies error:(NSError **)error API_AVAILABLE(ios(15.0)); // 需要额外权利 data-allowed
-(id)setLocalPolicies:(id)arg1 ;
-(void)setLocalPolicies:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)setRemotePolicies:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)removePoliciesFromLocalDevice:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)getRemotePolicies:(id)arg1 completion:(/*^block*/id)arg2 ;
//-(id)setMaxDataRate:(CTXPCServiceSubscriptionContext *)context rate:(long long)arg2;
//-(id)setMaxDataRate:(CTXPCServiceSubscriptionContext *)context rate:(long long)rate error:(NSError **)error;
- (id)setMaxDataRate:(CTXPCServiceSubscriptionContext *)context rate:(long long)rate; // 设置网络类型
- (void)setMaxDataRate:(CTXPCServiceSubscriptionContext *)context rate:(long long)rate completion:(void (^)(NSError *error))completion;
-(id)setPacketContextActiveByServiceType:(id)arg1 connectionType:(int)arg2 active:(BOOL)arg3 ;
-(void)setPacketContextActiveByServiceType:(id)arg1 connectionType:(int)arg2 active:(BOOL)arg3 completion:(/*^block*/id)arg4 ;
-(id)setPrefForKey:(id)arg1 heirarchy:(id)arg2 value:(id)arg3 storage:(id)arg4 ;
-(void)setPrefForKey:(id)arg1 heirarchy:(id)arg2 value:(id)arg3 storage:(id)arg4 completion:(/*^block*/id)arg5 ;
-(id)setPrivacyProxyState:(id)arg1 enabled:(BOOL)enabled ;
-(id)setReliableNetworkFallback:(id)arg1 enable:(BOOL)enable ;
-(id)setStewieBlocked:(BOOL)arg1 ;
-(void)setStewieBlocked:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)getSupportDynamicDataSimSwitchOnBBCall:(/*^block*/id)arg1 ;
- (BOOL)getSupportDynamicDataSimSwitchSync:(NSError **)error API_AVAILABLE(ios(13.0)) NS_SWIFT_NOTHROW; // 允许切换蜂窝数据
- (BOOL)getSupportDynamicDataSimSwitchOnBBCallSync:(NSError **)error NS_SWIFT_NOTHROW; // 允许在通话时切换蜂窝数据
-(void)getSupportDynamicDataSimSwitch:(/*^block*/id)arg1;
-(id)setSupportDynamicDataSimSwitch:(BOOL)enable;
-(void)setSupportDynamicDataSimSwitch:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)setSupportDynamicDataSimSwitch:(BOOL)arg1 forIccid:(id)arg2 completion:(/*^block*/id)arg3 ;
-(id)setSupportDynamicDataSimSwitchOnBBCall:(BOOL)arg1 ;
-(void)setSupportDynamicDataSimSwitchOnBBCall:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(id)setSupports5GStandalone:(id)arg1 enabled:(BOOL)arg2 ;
-(void)setSweetgumUserConsent:(id)arg1 userConsent:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(id)setTransportKeysUpdated:(BOOL)arg1 with:(id)arg2 ;
-(void)setUpeSIMLaunched:(/*^block*/id)arg1 ;
-(void)setUsageCollectionEnabled:(BOOL)arg1 completion:(/*^block*/id)arg2 API_AVAILABLE(ios(17.0));
-(void)setUserEntered:(id)arg1 monthlyBudget:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)setUserEntered:(id)arg1 monthlyBudget:(id)arg2 error:(id*)arg3 ;
-(void)setUserEntered:(id)arg1 monthlyRoamingBudget:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)setUserEntered:(id)arg1 monthlyRoamingBudget:(id)arg2 error:(id*)arg3 ;
-(void)setUserEnteredBillingEnd:(id)arg1 dayOfMonth:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)setUserEnteredBillingEnd:(id)arg1 dayOfMonth:(id)arg2 error:(id*)arg3 ;
//-(void)setUserQueue:(queue*)arg1 ;
-(void)setVinylTestMode:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)setVirtualSimMode:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(id)setVisualVoicemailState:(id)arg1 subscribed:(BOOL)arg2 ;
-(void)setVoLTEAudioCodec:(id)arg1 codecInfo:(id)arg2 completion:(/*^block*/id)arg3 ;
-(id)setWiFiCallingSettingPreferences:(id)arg1 key:(id)arg2 value:(id)arg3 ;
-(void)setWiFiCallingSettingPreferences:(id)arg1 key:(id)arg2 value:(id)arg3 completion:(/*^block*/id)arg4 ;
-(NSNumber *)shouldAllowSimLockFor:(CTXPCServiceSubscriptionContext *)context API_AVAILABLE(ios(14.0)); // 是否允许使用PIN
-(NSNumber *)shouldAllowSimLockFor:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error API_AVAILABLE(ios(17.0)); // 是否允许使用PIN 包含错误返回
-(NSNumber *)shouldShowBrandedCallingInfo:(NSError **)error API_AVAILABLE(ios(16.0)); // 显示品牌通话信息 不知道做什么的
-(id)setShouldShowBrandedCallingInfo:(BOOL)arg1 API_AVAILABLE(ios(16.0));
-(void)shouldShowUserWarningWhenDialingCallOnContext:(id)arg1 completion:(/*^block*/id)arg2 ;
-(BOOL)shouldShowUserWarningWhenDialingCallOnContext:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error NS_SWIFT_NOTHROW; // TODO 不知道做什么的
-(NSNumber *)shouldShoweSIMTravelTip:(NSError **)error API_AVAILABLE(ios(17.0)); // 是否显示eSIM旅行提示
-(void)simulateDataStall:(BOOL)arg1 pdp:(int)arg2 completion:(/*^block*/id)arg3 ;
-(void)submitCarrierSetupUserCancelEvent:(/*^block*/id)arg1 ;
-(void)submitPlanSetupDetails:(id)arg1 completion:(/*^block*/id)arg2 ;
-(NSNumber *)supportsHydraWithError:(NSError **)error API_AVAILABLE(ios(15.0)); // 高级数据通道调度能力
-(BOOL)supportsPlanProvisioning:(id)arg1 carrierDescriptors:(id)arg2 smdpUrl:(id)arg3 iccidPrefix:(id)arg4 ;
-(id)terminateProcess API_AVAILABLE(ios(15.0)); // 不支持的方法
-(void)terminateProcess:(/*^block*/id)arg1 API_AVAILABLE(ios(15.0)); // 一个闭包参数 返回错误代码 45 不支持
-(void)testStewieCommand:(id)arg1 completion:(/*^block*/id)arg2 API_AVAILABLE(ios(16.0));
-(void)transferCellularPlan:(id)arg1 fromDevice:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)transferCellularPlans:(id)arg1 fromDevice:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(id)transferPersonalWallet:(id)arg1 to:(id)arg2 ;
-(void)transferPlan:(id)arg1 fromDevice:(id)arg2 completionHandler:(/*^block*/id)arg3 ; // 转移eSIM的方法
-(void)transferPlans:(id)arg1 fromDevice:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)transferRemotePlan:(id)arg1 fromDevice:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)unhideTransferPlan:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)unlockPIN:(id)arg1 pin:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)unlockPIN:(id)arg1 pin:(id)arg2 error:(id*)arg3 ;
-(void)unlockPUK:(id)arg1 puk:(id)arg2 newPin:(id)arg3 completion:(/*^block*/id)arg4 ;
-(void)unlockPUK:(id)arg1 puk:(id)arg2 newPin:(id)arg3 error:(id*)arg4 ;
-(BOOL)updateGeofenceProfile:(id)arg1 ;
-(id)updateSecureIntentData:(NSData *)data ; // TODO
-(void)usageCollectionEnabled:(/*^block*/id)arg1 API_AVAILABLE(ios(17.0));
-(NSNumber *)usageCollectionEnabledSync:(NSError **)error API_AVAILABLE(ios(17.0)); // 是否开启蜂窝网络数据使用量统计
-(void)userEnteredBillingEndDayOfMont:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)userEnteredBillingEndDayOfMont:(id)arg1 error:(id*)arg2 ;
-(void)userEnteredMonthlyBudget:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)userEnteredMonthlyRoamingBudget:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)userEnteredMonthlyRoamingBudget:(id)arg1 error:(id*)arg2 ;
//-(queue*)userQueue;
-(id)bootstrapPlanTransferForEndpoint:(unsigned long long)arg1 ;
-(id)bootstrapPlanTransferForEndpoint:(unsigned long long)arg1 usingMessageSession:(id)arg2 ;
-(void)bootstrapPlanTransferForEndpoint:(unsigned long long)arg1 usingMessageSession:(id)arg2 completion:(/*^block*/id)arg3 ;
-(BOOL)requestBootstrapDataService:(NSError **)error API_AVAILABLE(ios(17.0)) NS_SWIFT_NOTHROW; // 需要requestBootstrapDataService权利 仍然返回49错误 无法分配地址 正确启动条件很苛刻 iOS 26已移除
-(BOOL)releaseBootstrapDataService:(NSError **)error API_AVAILABLE(ios(17.0)) NS_SWIFT_NOTHROW; // 释放eSIM下载服务
-(NSNumber *)usingBootstrapDataService:(NSError **)error API_AVAILABLE(ios(16.0)); // 是否正在使用eSIM配置下载服务
-(void)validateProximityTransfer:(unsigned long long)arg1 pin:(id)arg2 completion:(/*^block*/id)arg3 API_AVAILABLE(ios(16.0)); // 是否支持快速转移eSIM的配套方法
-(void)websheetInfoForIccid:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)websheetInfoForPlan:(id)arg1 inBuddy:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(id)wifiCallingCTFollowUpComplete:(id)arg1 ; // 参数不是context或者error 需要NSArray或者NSString

// iOS 18.6 头文件diff新增
- (id)getBootstrapState:(NSError **)error API_AVAILABLE(ios(17.4));
- (void)getRoamingStatus:(CTXPCServiceSubscriptionContext *)context completion:(id /* block */)completion API_AVAILABLE(ios(18.0));
- (id)getRoamingStatus:(CTXPCServiceSubscriptionContext *)context error:(NSError **)error API_AVAILABLE(ios(18.0));
- (BOOL)_decodeCardData:(id)data smdp:(id *)smdp matchingID:(id *)id OID:(id *)oid API_AVAILABLE(ios(17.4));
- (BOOL)acknowledgeIncomingMessages:(id)messages withMessageIDList:(id)idlist withError:(id *)error API_AVAILABLE(ios(18.0));
- (void)activateCrossPlatformTransport:(unsigned long long)transport completion:(id /* block */)completion;
- (void)activateTurboMode:(/* block */id)arg1 API_AVAILABLE(ios(18.3));

// 扩展CoreTelephony的方法
typedef struct _CTServerConnection *CTServerConnectionRef;
extern CTServerConnectionRef _CTServerConnectionCreate(CFAllocatorRef allocator, void *arg1, void *arg2); // 创建CTServerConnection的方法
extern long _CTServerConnectionInstallCarrierBundle(CTServerConnectionRef connection, CFTypeRef bundlePath); // 安装IPCC的方法
extern int _CTServerConnectionCopyFirmwareVersion(CTServerConnectionRef connection, CFStringRef *firmwareVersion); // 获取 调制解调器固件版本
extern int _CTServerConnectionResetCarrierBundle(CTServerConnectionRef connection); // 恢复IPCC为系统默认版本，低版本兼容方案
extern void _CTServerConnectionResetModem(CTServerConnectionRef connection, CFStringRef reason); // 刷新信号
extern int _CTServerConnectionGetCellularDataIsEnabled(CTServerConnectionRef connection, uint8_t *isEnabled); // 蜂窝数据是否开启
extern int _CTServerConnectionSetCellularDataIsEnabled(CTServerConnectionRef connection, uint8_t enabled); // 设置蜂窝数据是否开启
extern int _CTServerConnectionDebugResetSim(CTServerConnectionRef connection); // 重置SIM卡状态 日志报错 #N no controller to send debug sim reset
extern int _CTServerConnectionFetchTimeFromNetwork(CTServerConnectionRef connection, int32_t requestType, int32_t *result); // 获取数据无效
extern int _CTServerConnectionGetTemperature(CTServerConnectionRef connection, int32_t sensorType, uint8_t *valid, int32_t *value1, int32_t *value2); // 获取数据无效

@end

