/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:38 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CoreTelephonyClientSubscriberDelegateInternal.h
*/


@protocol CoreTelephonyClientSubscriberDelegateInternal <NSObject>

@optional
-(void)subscriberCountryCodeDidChange:(id)arg1;
-(void)simStatusDidChange:(id)arg1 status:(id)arg2;
-(void)didDetectSimDeactivation:(id)arg1 info:(id)arg2;
-(void)authTokenChanged:(id)arg1;
-(void)prlVersionDidChange:(id)arg1 version:(id)arg2;
-(void)shortLabelsDidChange;
-(void)simLockSaveRequestDidComplete:(id)arg1 success:(BOOL)arg2;
-(void)simPinChangeRequestDidComplete:(id)arg1 success:(BOOL)arg2;
-(void)simPinEntryErrorDidOccur:(id)arg1 status:(id)arg2;
-(void)simPukEntryErrorDidOccur:(id)arg1 status:(id)arg2;
-(void)userDefaultVoiceSlotDidChange:(id)arg1;
@end
