/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:38 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTBandInfo.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

@class NSMutableDictionary;

/// 支持的频段合集
API_AVAILABLE(ios(14.0))
@interface CTBandInfo : NSObject <NSCopying, NSSecureCoding> {

    NSMutableDictionary* _fActiveBands;     // 网络广播允许使用的频段
    NSMutableDictionary* _fSupportedBands;  // 设备支持的频段
}
@property (nonatomic,retain) NSMutableDictionary * fActiveBands;                 //@synthesize fActiveBands=_fActiveBands - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * fSupportedBands;              //@synthesize fSupportedBands=_fSupportedBands - In the implementation block
+(BOOL)supportsSecureCoding;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)init;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSMutableDictionary *)fSupportedBands;
-(id)activeBands;
-(id)activeBandsForRat:(id)arg1 ;
-(BOOL)addActiveBand:(id)arg1 forRat:(id)arg2 ;
-(BOOL)addActiveBands:(id)arg1 forRat:(id)arg2 ;
-(BOOL)addSupportedBand:(id)arg1 forRat:(id)arg2 ;
-(BOOL)addSupportedBands:(id)arg1 forRat:(id)arg2 ;
-(NSMutableDictionary *)fActiveBands;
-(id)initWithActiveBands:(id)arg1 ;
-(id)initWithSupported:(id)arg1 andActiveBands:(id)arg2 ;
-(id)initWithSupportedBands:(id)arg1 ;
-(void)setFActiveBands:(NSMutableDictionary *)arg1 ;
-(void)setFSupportedBands:(NSMutableDictionary *)arg1 ;
-(id)supportedBands;
-(id)supportedBandsForRat:(id)arg1 ;
@end
