/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTCarrier.h
*/


@class NSString;

@interface CTCarrier : NSObject {

    NSString* _carrierName;
    NSString* _mobileCountryCode;
    NSString* _mobileNetworkCode;
    NSString* _isoCountryCode;
    BOOL _allowsVOIP;
}
@property (nonatomic,retain) NSString * carrierName;                    //@synthesize carrierName=_carrierName - In the implementation block
@property (nonatomic,retain) NSString * mobileCountryCode;              //@synthesize mobileCountryCode=_mobileCountryCode - In the implementation block
@property (nonatomic,retain) NSString * mobileNetworkCode;              //@synthesize mobileNetworkCode=_mobileNetworkCode - In the implementation block
@property (nonatomic,retain) NSString * isoCountryCode;                 //@synthesize isoCountryCode=_isoCountryCode - In the implementation block
@property (assign,nonatomic) BOOL allowsVOIP;                           //@synthesize allowsVOIP=_allowsVOIP - In the implementation block
-(NSString *)carrierName;
-(NSString *)isoCountryCode;
-(void)setAllowsVOIP:(BOOL)arg1 ;
-(BOOL)allowsVOIP;
-(void)setMobileNetworkCode:(NSString *)arg1 ;
-(NSString *)mobileNetworkCode;
-(BOOL)isEqual:(id)arg1 ;
-(id)init;
-(NSString *)mobileCountryCode;
-(void)setIsoCountryCode:(NSString *)arg1 ;
-(id)description;
-(void)setCarrierName:(NSString *)arg1 ;
-(void)setMobileCountryCode:(NSString *)arg1 ;
@end
