/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://www.developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTCallCapabilities.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

// 是否支持Wi-Fi Calling和VoLTE
@interface CTCallCapabilities : NSObject <NSCopying, NSSecureCoding> {

    BOOL _isWifiCallingAvailable;  // 是否支持Wi-Fi Calling
    BOOL _isVoLTECallingAvailable; // 是否支持VoLTE
    BOOL _isCSCallingAvailable;    // 是否支持 电路交换语音 古老的东西 没什么用
    BOOL _isEmergencyCallingOnWifiAllowed; // 是否允许使用Wi-Fi Calling是用紧急呼叫
    BOOL _isEmergencyCallingOnWifiAvailable; // 是否支持使用Wi-Fi Calling是用紧急呼叫
    BOOL _isCarrierSupportsEmergencyCallOnWifiNoLimit; // 运营商是否支持使用Wi-Fi Calling使用紧急呼叫并且无限制
}
@property (assign,nonatomic) BOOL isWifiCallingAvailable;                                   //@synthesize isWifiCallingAvailable=_isWifiCallingAvailable - In the implementation block
@property (assign,nonatomic) BOOL isVoLTECallingAvailable;                                  //@synthesize isVoLTECallingAvailable=_isVoLTECallingAvailable - In the implementation block
@property (assign,nonatomic) BOOL isCSCallingAvailable;                                     //@synthesize isCSCallingAvailable=_isCSCallingAvailable - In the implementation block
@property (assign,nonatomic) BOOL isEmergencyCallingOnWifiAllowed;                          //@synthesize isEmergencyCallingOnWifiAllowed=_isEmergencyCallingOnWifiAllowed - In the implementation block
@property (assign,nonatomic) BOOL isEmergencyCallingOnWifiAvailable;                        //@synthesize isEmergencyCallingOnWifiAvailable=_isEmergencyCallingOnWifiAvailable - In the implementation block
@property (assign,nonatomic) BOOL isCarrierSupportsEmergencyCallOnWifiNoLimit;              //@synthesize isCarrierSupportsEmergencyCallOnWifiNoLimit=_isCarrierSupportsEmergencyCallOnWifiNoLimit - In the implementation block
+(BOOL)supportsSecureCoding;
-(void)setIsCSCallingAvailable:(BOOL)arg1 ;
-(void)setIsVoLTECallingAvailable:(BOOL)arg1 ;
-(void)setIsEmergencyCallingOnWifiAllowed:(BOOL)arg1 ;
-(void)setIsCarrierSupportsEmergencyCallOnWifiNoLimit:(BOOL)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isVoLTECallingAvailable;
-(BOOL)isCarrierSupportsEmergencyCallOnWifiNoLimit;
-(BOOL)isWifiCallingAvailable;
-(id)initWithCoder:(id)arg1 ;
-(void)setIsEmergencyCallingOnWifiAvailable:(BOOL)arg1 ;
-(BOOL)isEmergencyCallingOnWifiAvailable;
-(void)setIsWifiCallingAvailable:(BOOL)arg1 ;
-(BOOL)isEmergencyCallingOnWifiAllowed;
-(BOOL)isCSCallingAvailable;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
@end
