/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://www.developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTCellularQoSFlow.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

@class NSNumber, CTQoS;

@interface CTCellularQoSFlow : NSObject <NSCopying, NSSecureCoding> {

    unsigned long long _flowId;
    unsigned long long _bearerId;
    NSNumber* _queueSetId;
    NSNumber* _is5G;
    CTQoS* _txQos;
    CTQoS* _rxQos;
}
@property (assign,nonatomic) unsigned long long flowId;                //@synthesize flowId=_flowId - In the implementation block
@property (assign,nonatomic) unsigned long long bearerId;              //@synthesize bearerId=_bearerId - In the implementation block
@property (nonatomic,retain) NSNumber * queueSetId;                    //@synthesize queueSetId=_queueSetId - In the implementation block
@property (nonatomic,retain) NSNumber * is5G;                          //@synthesize is5G=_is5G - In the implementation block
@property (nonatomic,retain) CTQoS * txQos;                            //@synthesize txQos=_txQos - In the implementation block
@property (nonatomic,retain) CTQoS * rxQos;                            //@synthesize rxQos=_rxQos - In the implementation block
+(BOOL)supportsSecureCoding;
-(void)setFlowId:(unsigned long long)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(unsigned long long)flowId;
-(id)initWithCoder:(id)arg1 ;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(unsigned long long)bearerId;
-(NSNumber *)is5G;
-(NSNumber *)queueSetId;
-(CTQoS *)rxQos;
-(void)setBearerId:(unsigned long long)arg1 ;
-(void)setIs5G:(NSNumber *)arg1 ;
-(void)setQueueSetId:(NSNumber *)arg1 ;
-(void)setRxQos:(CTQoS *)arg1 ;
-(void)setTxQos:(CTQoS *)arg1 ;
-(CTQoS *)txQos;
@end
