/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTCellIdInfo.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

@class NSNumber;

@interface CTCellIdInfo : NSObject <NSCopying, NSSecureCoding> {

    NSNumber* _cellId;
    NSNumber* _baseId;
}
@property (nonatomic,readonly) NSNumber * cellId;              //@synthesize cellId=_cellId - In the implementation block
@property (nonatomic,readonly) NSNumber * baseId;              //@synthesize baseId=_baseId - In the implementation block
+(BOOL)supportsSecureCoding;
+(id)cellIdInfoFromCellId:(unsigned long long)arg1 baseId:(int)arg2 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(NSNumber *)cellId; // 连接的小区ID
-(NSNumber *)baseId;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
@end
