/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:38 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTCellularUsageWorkspaceInfo.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

@class NSNumber, NSDate, NSString;
API_AVAILABLE(ios(17.0))
@interface CTCellularUsageWorkspaceInfo : NSObject <NSCopying, NSSecureCoding> {

    NSNumber* _subscriberTag;
    NSNumber* _metaDataForHomeCountry;
    NSNumber* _metaDataForRoaming;
    NSDate* _billingCycleEndDate;
    NSDate* _previousBillingCycleDate;
    NSNumber* _billingCycleSupported;
    NSNumber* _carrierSpaceSupported;
    NSString* _workspaceName;
    NSString* _workspacePath;
}
@property (nonatomic,readonly) NSNumber * subscriberTag;                       //@synthesize subscriberTag=_subscriberTag - In the implementation block
@property (nonatomic,readonly) NSNumber * metaDataForHomeCountry;              //@synthesize metaDataForHomeCountry=_metaDataForHomeCountry - In the implementation block
@property (nonatomic,readonly) NSNumber * metaDataForRoaming;                  //@synthesize metaDataForRoaming=_metaDataForRoaming - In the implementation block
@property (nonatomic,readonly) NSDate * billingCycleEndDate;                   //@synthesize billingCycleEndDate=_billingCycleEndDate - In the implementation block
@property (nonatomic,readonly) NSDate * previousBillingCycleDate;              //@synthesize previousBillingCycleDate=_previousBillingCycleDate - In the implementation block
@property (nonatomic,readonly) NSNumber * billingCycleSupported;               //@synthesize billingCycleSupported=_billingCycleSupported - In the implementation block
@property (nonatomic,readonly) NSNumber * carrierSpaceSupported;               //@synthesize carrierSpaceSupported=_carrierSpaceSupported - In the implementation block
@property (nonatomic,readonly) NSString * workspaceName;                       //@synthesize workspaceName=_workspaceName - In the implementation block
@property (nonatomic,readonly) NSString * workspacePath;                       //@synthesize workspacePath=_workspacePath - In the implementation block
+(BOOL)supportsSecureCoding;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSDate *)billingCycleEndDate;
-(NSNumber *)billingCycleSupported;
-(NSNumber *)carrierSpaceSupported;
-(id)initWithSubscriberTag:(id)arg1 metaDataForHomeCountry:(id)arg2 metaDataForRoaming:(id)arg3 billingCycleEndDate:(id)arg4 previousBillingCycleDate:(id)arg5 billingCycleSupported:(id)arg6 carrierSpaceSupported:(id)arg7 workspaceName:(id)arg8 workspacePath:(id)arg9 ;
-(NSNumber *)metaDataForHomeCountry;
-(NSNumber *)metaDataForRoaming;
-(NSDate *)previousBillingCycleDate;
-(NSNumber *)subscriberTag;
-(NSString *)workspaceName;
-(NSString *)workspacePath;
@end
