/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://www.developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTCellInfo.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

@class NSArray;

@interface CTCellInfo : NSObject <NSCopying, NSSecureCoding> {

    NSArray<NSDictionary<NSString *, id> *> * _legacyInfo;
}
@property (nonatomic,retain) NSArray<NSDictionary<NSString *, id> *> * legacyInfo;              //@synthesize legacyInfo=_legacyInfo - In the implementation block
+(BOOL)supportsSecureCoding;
-(NSArray<NSDictionary<NSString *, id> *> *)legacyInfo;
-(void)encodeWithCoder:(id)arg1 ;
-(void)setLegacyInfo:(NSArray<NSDictionary<NSString *, id> *> *)info ;
-(id)initWithCoder:(id)arg1 ;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
@end
