/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:47:17 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/PrivateFrameworks/CellularPlanManager.framework/CellularPlanManager
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://developer.limneos.net/index.php?ios=17.1&framework=CellularPlanManager.framework&header=CTCellularPlanProfile.h
*/

//#import <CellularPlanManager/CellularPlanManager-Structs.h>
//#import <CellularPlanManager/NSCopying.h>
//#import <CellularPlanManager/NSSecureCoding.h>

@class NSData, NSString;

@interface CTCellularPlanProfile : NSObject <NSCopying, NSSecureCoding> {

    BOOL _isSelected;
    BOOL _isBootstrap;
    BOOL _isDisableNotAllowed;
    BOOL _isDeleteNotAllowed;
    BOOL _requiresUserConsent;
    NSData* _profileId;
    NSString* _iccid;
}
@property (assign,nonatomic) BOOL isSelected;                       //@synthesize isSelected=_isSelected - In the implementation block
@property (assign,nonatomic) BOOL isBootstrap;                      //@synthesize isBootstrap=_isBootstrap - In the implementation block
@property (assign,nonatomic) BOOL isDisableNotAllowed;              //@synthesize isDisableNotAllowed=_isDisableNotAllowed - In the implementation block
@property (assign,nonatomic) BOOL isDeleteNotAllowed;               //@synthesize isDeleteNotAllowed=_isDeleteNotAllowed - In the implementation block
@property (assign,nonatomic) BOOL requiresUserConsent;              //@synthesize requiresUserConsent=_requiresUserConsent - In the implementation block
@property (nonatomic,copy) NSData * profileId;                      //@synthesize profileId=_profileId - In the implementation block
@property (nonatomic,copy) NSString * iccid;                        //@synthesize iccid=_iccid - In the implementation block
+(BOOL)supportsSecureCoding;
-(BOOL)isSelected;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isBootstrap;
-(id)initWithCoder:(id)arg1 ;
-(void)setIsSelected:(BOOL)arg1 ;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)redactedDescription;
-(NSString *)iccid;
-(void)setIccid:(NSString *)arg1 ;
-(NSData *)profileId;
-(void)setProfileId:(NSData *)arg1 ;
-(BOOL)requiresUserConsent;
-(void)setRequiresUserConsent:(BOOL)arg1 ;
-(void)setIsBootstrap:(BOOL)arg1 ;
-(id)initWithProfileId:(id)arg1 iccid:(id)arg2 selected:(BOOL)arg3 bootstrap:(BOOL)arg4 disableNotAllowed:(BOOL)arg5 deleteNotAllowed:(BOOL)arg6 requiresUserConsent:(BOOL)arg7 ;
-(BOOL)isDeleteNotAllowed;  // 是否不允许删除
-(BOOL)isDisableNotAllowed; // 是否不允许禁用
-(void)setIsDeleteNotAllowed:(BOOL)arg1 ;
-(void)setIsDisableNotAllowed:(BOOL)arg1 ;
@end
