/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTDataStatusBasic.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

API_AVAILABLE(ios(15.4))
@interface CTDataStatusBasic : NSObject <NSCopying, NSSecureCoding> {

    BOOL _attached;
    BOOL _hasIndicator;
    BOOL _inHomeCountry;
    BOOL _roamAllowed;
    BOOL _cellularDataPossible;
    BOOL _newRadioCoverage;
}
@property (assign,nonatomic) BOOL attached;                          //@synthesize attached=_attached - In the implementation block
@property (assign,nonatomic) BOOL hasIndicator;                      //@synthesize hasIndicator=_hasIndicator - In the implementation block
@property (assign,nonatomic) BOOL inHomeCountry;                     //@synthesize inHomeCountry=_inHomeCountry - In the implementation block
@property (assign,nonatomic) BOOL roamAllowed;                       //@synthesize roamAllowed=_roamAllowed - In the implementation block
@property (assign,nonatomic) BOOL cellularDataPossible;              //@synthesize cellularDataPossible=_cellularDataPossible - In the implementation block
@property (assign,nonatomic) BOOL newRadioCoverage;                  //@synthesize newRadioCoverage=_newRadioCoverage - In the implementation block
+(BOOL)supportsSecureCoding;
-(void)setHasIndicator:(BOOL)arg1 ;
-(BOOL)attached;
-(BOOL)roamAllowed;
-(BOOL)inHomeCountry;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)hasIndicator;
-(BOOL)cellularDataPossible;
-(BOOL)newRadioCoverage;
-(id)initWithCoder:(id)arg1 ;
-(void)setInHomeCountry:(BOOL)arg1 ;
-(void)setCellularDataPossible:(BOOL)arg1 ;
-(void)setAttached:(BOOL)arg1 ;
-(id)description;
-(void)setRoamAllowed:(BOOL)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setNewRadioCoverage:(BOOL)arg1 ;
@end
