/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://www.developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTDataConnectionStatus.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>
#import "CTCellularQoSFlow.h"

@class NSNumber, NSString, NSArray;
API_AVAILABLE(ios(13.0))
@interface CTDataConnectionStatus : NSObject <NSCopying, NSSecureCoding> {

    BOOL _suspended;
    BOOL _publicNetAllowed;
    unsigned _wirelessTechnologyMask;
    int _state;
    int _ipFamily;
    int _contextType;
    int _transportType;
    NSNumber* _pdp;
    NSString* _interfaceName;
    NSString* _apnName;
    NSArray <CTCellularQoSFlow *> * _qosFlows;
    NSArray* _trafficDescriptors;
}
@property (nonatomic,retain) NSNumber * pdp;                               //@synthesize pdp=_pdp - In the implementation block
@property (nonatomic,retain) NSString * interfaceName;                     //@synthesize interfaceName=_interfaceName - In the implementation block
@property (nonatomic,retain) NSString * apnName;                           //@synthesize apnName=_apnName - In the implementation block
@property (assign,nonatomic) unsigned wirelessTechnologyMask;              //@synthesize wirelessTechnologyMask=_wirelessTechnologyMask - In the implementation block
@property (assign,nonatomic) int state;                                    //@synthesize state=_state - In the implementation block
@property (assign,nonatomic) int ipFamily;                                 //@synthesize ipFamily=_ipFamily - In the implementation block
@property (assign,nonatomic) BOOL suspended;                               //@synthesize suspended=_suspended - In the implementation block
@property (assign,nonatomic) BOOL publicNetAllowed;                        //@synthesize publicNetAllowed=_publicNetAllowed - In the implementation block
@property (assign,nonatomic) int contextType;                              //@synthesize contextType=_contextType - In the implementation block
@property (assign,nonatomic) int transportType;                            //@synthesize transportType=_transportType - In the implementation block
@property (nonatomic,retain) NSArray * qosFlows;                           //@synthesize qosFlows=_qosFlows - In the implementation block
@property (nonatomic,retain) NSArray * trafficDescriptors;                 //@synthesize trafficDescriptors=_trafficDescriptors - In the implementation block
+(BOOL)supportsSecureCoding;
-(NSArray <CTCellularQoSFlow *> *)qosFlows;
-(void)setSuspended:(BOOL)arg1 ;
-(BOOL)suspended;
-(void)setQosFlows:(NSArray *)arg1 ;
-(void)setPublicNetAllowed:(BOOL)arg1 ;
-(int)contextType;
-(void)setContextType:(int)arg1 ;
-(void)setInterfaceName:(NSString *)arg1 ;
-(NSString *)interfaceName;
-(void)encodeWithCoder:(id)arg1 ;
-(void)setTransportType:(int)arg1 ;
-(BOOL)publicNetAllowed;
-(int)transportType;
-(void)setApnName:(NSString *)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(int)state;
-(void)setPdp:(NSNumber *)arg1 ;
-(NSString *)apnName;
-(void)setWirelessTechnologyMask:(unsigned)arg1 ;
-(void)setIpFamily:(int)arg1 ;
-(unsigned)wirelessTechnologyMask;
-(int)ipFamily;
-(NSNumber *)pdp;
-(id)description;
-(void)setTrafficDescriptors:(NSArray *)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSArray *)trafficDescriptors;
-(void)setState:(int)arg1 ;
@end
