/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTDataStatus.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

@interface CTDataStatus : NSObject <NSCopying, NSSecureCoding> {

    BOOL _attached;
    BOOL _dataSim;
    BOOL _roamAllowed;
    BOOL _dataPlanSignalingReductionOverride;
    BOOL _cellularDataPossible;
    BOOL _inHomeCountry;
    int _indicator;
    int _indicatorOverride;
    int _radioTechnology;
    int _dataMode API_AVAILABLE(ios(15.0));
    int _dataBearerTechnology API_AVAILABLE(ios(14.0));
    unsigned _dataBearerSoMask;
    unsigned _activeContexts;
    unsigned _totalActiveContexts;
    int _reason;
}
@property (nonatomic,readonly) BOOL newRadioCoverage;
@property (nonatomic,readonly) BOOL newRadioSaCoverage;
@property (nonatomic,readonly) BOOL newRadioNsaCoverage;
@property (nonatomic,readonly) BOOL newRadioDataBearer;
@property (nonatomic,readonly) BOOL newRadioSaDataBearer;
@property (nonatomic,readonly) BOOL newRadioNsaDataBearer;
@property (nonatomic,readonly) BOOL newRadioMmWaveDataBearer;
@property (nonatomic,readonly) BOOL newRadioSub6DataBearer;
@property (assign,nonatomic) BOOL attached;                                        //@synthesize attached=_attached - In the implementation block
@property (assign,nonatomic) BOOL dataSim;                                         //@synthesize dataSim=_dataSim - In the implementation block
@property (assign,nonatomic) int indicator;                                        //@synthesize indicator=_indicator - In the implementation block
@property (assign,nonatomic) int indicatorOverride;                                //@synthesize indicatorOverride=_indicatorOverride - In the implementation block
@property (assign,nonatomic) BOOL roamAllowed;                                     //@synthesize roamAllowed=_roamAllowed - In the implementation block
@property (assign,nonatomic) int radioTechnology;                                  //@synthesize radioTechnology=_radioTechnology - In the implementation block
@property (assign,nonatomic) int dataMode API_AVAILABLE(ios(15.0));                //@synthesize dataMode=_dataMode - In the implementation block
@property (assign,nonatomic) int dataBearerTechnology API_AVAILABLE(ios(14.0));    //@synthesize dataBearerTechnology=_dataBearerTechnology - In the implementation block
@property (assign,nonatomic) unsigned dataBearerSoMask;                            //@synthesize dataBearerSoMask=_dataBearerSoMask - In the implementation block
@property (assign,nonatomic) BOOL dataPlanSignalingReductionOverride;              //@synthesize dataPlanSignalingReductionOverride=_dataPlanSignalingReductionOverride - In the implementation block
@property (assign,nonatomic) BOOL cellularDataPossible;                            //@synthesize cellularDataPossible=_cellularDataPossible - In the implementation block
@property (assign,nonatomic) unsigned activeContexts;                              //@synthesize activeContexts=_activeContexts - In the implementation block
@property (assign,nonatomic) unsigned totalActiveContexts;                         //@synthesize totalActiveContexts=_totalActiveContexts - In the implementation block
@property (assign,nonatomic) BOOL inHomeCountry;                                   //@synthesize inHomeCountry=_inHomeCountry - In the implementation block
@property (assign,nonatomic) int reason;                                           //@synthesize reason=_reason - In the implementation block
+(BOOL)supportsSecureCoding;
-(BOOL)newRadioDataBearer;
-(void)setActiveContexts:(unsigned)arg1 ;
-(BOOL)attached;
-(BOOL)roamAllowed; // 是否允许数据漫游
-(void)setDataSim:(BOOL)arg1 ;
-(void)setReason:(int)arg1 ;
-(int)reason;
-(int)dataMode API_AVAILABLE(ios(15.0));
-(void)setIndicator:(int)arg1 ;
-(BOOL)inHomeCountry;
-(unsigned)activeContexts;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)cellularDataPossible;
-(int)dataBearerTechnology API_AVAILABLE(ios(14.0));
-(BOOL)newRadioSub6DataBearer API_AVAILABLE(ios(14.0));
-(BOOL)newRadioCoverage API_AVAILABLE(ios(14.0));
-(BOOL)dataPlanSignalingReductionOverride;
-(id)initWithCoder:(id)arg1 ;
-(void)setDataPlanSignalingReductionOverride:(BOOL)arg1 ;
-(BOOL)newRadioNsaCoverage API_AVAILABLE(ios(14.0));
-(void)setTotalActiveContexts:(unsigned)arg1 ;
-(id)copyBasic;
-(void)setIndicatorOverride:(int)arg1 ;
-(BOOL)newRadioNsaDataBearer API_AVAILABLE(ios(14.0));
-(void)setInHomeCountry:(BOOL)arg1 ;
-(void)setRadioTechnology:(int)arg1 ;
-(void)setCellularDataPossible:(BOOL)arg1 ;
-(BOOL)newRadioMmWaveDataBearer API_AVAILABLE(ios(14.0));
-(void)setDataBearerTechnology:(int)arg1 API_AVAILABLE(ios(14.0));
-(int)indicator;
-(unsigned)dataBearerSoMask;
-(void)setAttached:(BOOL)arg1 ;
-(id)description;
-(void)setRoamAllowed:(BOOL)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)dataSim; // 首选蜂窝数据卡
-(void)setDataMode:(int)arg1 API_AVAILABLE(ios(15.0));
-(unsigned)totalActiveContexts;
-(int)radioTechnology; // 蜂窝网络类型
-(BOOL)newRadioSaDataBearer;
-(int)indicatorOverride; // 状态栏显示的网络类型 0 = 未知 19 = 5GA
-(void)setDataBearerSoMask:(unsigned)arg1 ;
-(BOOL)newRadioSaCoverage;
@end
