/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://www.developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTDataConnectionAvailabilityStatus.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

/// 是否开启蜂窝网络的数据类
//API_AVAILABLE(ios(13.0))
@interface CTDataConnectionAvailabilityStatus : NSObject <NSCopying, NSSecureCoding> {

    BOOL _available; // 是否开启蜂窝网络
    int _csiError; // 未启用的原因 = 0    正常
                   //            = -1   蜂窝网络已关闭
                   //            = -2   未开启数据漫游
                   //            = -3   
                   //            = -5   无服务/飞行模式/SIM卡不允许蜂窝数据
}
@property (assign,nonatomic) BOOL available;              //@synthesize available=_available - In the implementation block
@property (assign,nonatomic) int csiError;                //@synthesize csiError=_csiError - In the implementation block
+(BOOL)supportsSecureCoding;
-(BOOL)available;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)setAvailable:(BOOL)arg1 ;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(int)csiError;
-(void)setCsiError:(int)arg1 ;
@end
