/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:38 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTEmergencyModeResult.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

@class CTEmergencyMode, CTXPCServiceSubscriptionContext;
API_AVAILABLE(ios(13.0))
@interface CTEmergencyModeResult : NSObject <NSCopying, NSSecureCoding> {

    CTEmergencyMode* _mode;
    CTXPCServiceSubscriptionContext* _context;
}
@property (nonatomic,readonly) CTEmergencyMode * mode;                                 //@synthesize mode=_mode - In the implementation block
@property (nonatomic,readonly) CTXPCServiceSubscriptionContext * context;              //@synthesize context=_context - In the implementation block
+(BOOL)supportsSecureCoding;
-(CTXPCServiceSubscriptionContext *)context;
-(CTEmergencyMode *)mode;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)initWithMode:(id)arg1 andContext:(id)arg2 ;
@end
