/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

@interface CTIMSRegistrationStatus : NSObject <NSCopying, NSSecureCoding> {

    BOOL _isRegisteredForVoice;
    BOOL _isRegisteredForSMS;
}
@property (assign,nonatomic) BOOL isRegisteredForVoice;              //@synthesize isRegisteredForVoice=_isRegisteredForVoice - In the implementation block
@property (assign,nonatomic) BOOL isRegisteredForSMS;                //@synthesize isRegisteredForSMS=_isRegisteredForSMS - In the implementation block
+(BOOL)supportsSecureCoding;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)isRegisteredForSMS;
-(BOOL)isRegisteredForVoice;
-(void)setIsRegisteredForSMS:(BOOL)arg1 ;
-(void)setIsRegisteredForVoice:(BOOL)arg1 ;
@end
