/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://www.developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTMobileEquipmentInfo.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

@class NSString, NSNumber;

@interface CTMobileEquipmentInfo : NSObject <NSCopying, NSSecureCoding> {

    long long _slotId; // 卡槽ID
    NSString* _currentMobileId; // 正在使用的IMEI
    NSString* _currentSubscriberId; // 当前IMSI
    NSString* _IMEI; //IMEI
    NSString* _ICCID;
    NSString* _IMSI;
    NSString* _cdmaIMSI;
    NSString* _MEID;
    NSString* _EUIMID;
    NSNumber* _PRLVersion;
    NSNumber* _ERIVersion;
    NSString* _MIN;
    NSString* _NAI;
    NSString* _baseVersion;
    NSString* _baseId;
    NSString* _baseProfile;
    NSString* _effectiveICCID;
    NSString* _CSN;
    NSString* _displayCSN;
}
@property (assign,nonatomic) long long slotId;                            //@synthesize slotId=_slotId - In the implementation block
@property (nonatomic,retain) NSString * currentMobileId;                  //@synthesize currentMobileId=_currentMobileId - In the implementation block
@property (nonatomic,retain) NSString * currentSubscriberId;              //@synthesize currentSubscriberId=_currentSubscriberId - In the implementation block
@property (nonatomic,retain) NSString * IMEI;                             //@synthesize IMEI=_IMEI - In the implementation block
@property (nonatomic,retain) NSString * ICCID;                            //@synthesize ICCID=_ICCID - In the implementation block
@property (nonatomic,retain) NSString * IMSI;                             //@synthesize IMSI=_IMSI - In the implementation block
@property (nonatomic,retain) NSString * cdmaIMSI;                         //@synthesize cdmaIMSI=_cdmaIMSI - In the implementation block
@property (nonatomic,retain) NSString * MEID;                             //@synthesize MEID=_MEID - In the implementation block
@property (nonatomic,retain) NSString * EUIMID;                           //@synthesize EUIMID=_EUIMID - In the implementation block
@property (nonatomic,retain) NSNumber * PRLVersion;                       //@synthesize PRLVersion=_PRLVersion - In the implementation block
@property (nonatomic,retain) NSNumber * ERIVersion;                       //@synthesize ERIVersion=_ERIVersion - In the implementation block
@property (nonatomic,retain) NSString * MIN;                              //@synthesize MIN=_MIN - In the implementation block
@property (nonatomic,retain) NSString * NAI;                              //@synthesize NAI=_NAI - In the implementation block
@property (nonatomic,retain) NSString * baseVersion;                      //@synthesize baseVersion=_baseVersion - In the implementation block
@property (nonatomic,retain) NSString * baseId;                           //@synthesize baseId=_baseId - In the implementation block
@property (nonatomic,retain) NSString * baseProfile;                      //@synthesize baseProfile=_baseProfile - In the implementation block
@property (nonatomic,retain) NSString * effectiveICCID;                   //@synthesize effectiveICCID=_effectiveICCID - In the implementation block
@property (nonatomic,retain) NSString * CSN;                              //@synthesize CSN=_CSN - In the implementation block
@property (nonatomic,retain) NSString * displayCSN;                       //@synthesize displayCSN=_displayCSN - In the implementation block
+(BOOL)supportsSecureCoding;
-(void)setCurrentMobileId:(NSString *)arg1 ;
-(void)setICCID:(NSString *)arg1 ;
-(void)setPRLVersion:(NSNumber *)arg1 ;
-(NSString *)currentSubscriberId;
-(NSString *)currentMobileId;
-(NSString *)effectiveICCID;
-(void)setCdmaIMSI:(NSString *)arg1 ;
-(NSString *)IMSI;
-(void)encodeWithCoder:(id)arg1 ;
-(NSString *)MIN;
-(NSString *)EUIMID;
-(void)setBaseId:(NSString *)arg1 ;
-(NSString *)displayCSN;
-(NSString *)CSN;
-(void)setDisplayCSN:(NSString *)arg1 ;
-(void)setMEID:(NSString *)arg1 ;
-(void)setERIVersion:(NSNumber *)arg1 ;
-(void)setBaseProfile:(NSString *)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)setIMEI:(NSString *)arg1 ;
-(long long)slotId;
-(void)setCurrentSubscriberId:(NSString *)arg1 ;
-(void)setSlotId:(long long)arg1 ;
-(void)setCSN:(NSString *)arg1 ;
-(void)setEffectiveICCID:(NSString *)arg1 ;
-(NSString *)baseProfile;
-(NSString *)ICCID;
-(void)setBaseVersion:(NSString *)arg1 ;
-(NSString *)baseId;
-(id)description;
-(void)setIMSI:(NSString *)arg1 ;
-(NSString *)baseVersion;
-(NSString *)NAI;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setNAI:(NSString *)arg1 ;
-(NSString *)cdmaIMSI;
-(NSNumber *)PRLVersion;
-(void)setMIN:(NSString *)arg1 ;
-(NSNumber *)ERIVersion;
-(NSString *)IMEI;
-(void)setEUIMID:(NSString *)arg1 ;
-(NSString *)MEID;
@end
