/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 https://developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTMobileEquipmentInfoList.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

#import "CTMobileEquipmentInfo.h"

@class NSArray;

@interface CTMobileEquipmentInfoList : NSObject <NSCopying, NSSecureCoding> {

    NSArray* _meInfoList;
}
@property (nonatomic,retain) NSArray<CTMobileEquipmentInfo *> *meInfoList;              //@synthesize meInfoList=_meInfoList - In the implementation block
+(BOOL)supportsSecureCoding;
-(void)encodeWithCoder:(id)arg1 ;
-(void)setMeInfoList:(NSArray<CTMobileEquipmentInfo *> *)list;
-(id)initWithCoder:(id)arg1 ;
-(id)description;
-(NSArray <CTMobileEquipmentInfo *> *)meInfoList;
-(id)copyWithZone:(NSZone*)arg1 ;
@end
