/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTNetworkSelectionInfo.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

@class CTNetwork;

@interface CTNetworkSelectionInfo : NSObject <NSCopying, NSSecureCoding> {

    unsigned long long _selectionState;
    unsigned long long _selectionMode;
    CTNetwork* _selection;
}
@property (assign,nonatomic) unsigned long long selectionState;              //@synthesize selectionState=_selectionState - In the implementation block
@property (assign,nonatomic) unsigned long long selectionMode;               //@synthesize selectionMode=_selectionMode - In the implementation block
@property (nonatomic,retain) CTNetwork * selection;                          //@synthesize selection=_selection - In the implementation block
+(BOOL)supportsSecureCoding;
-(CTNetwork *)selection;
-(void)setSelection:(CTNetwork *)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(unsigned long long)selectionState;
-(void)setSelectionState:(unsigned long long)arg1 ;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(unsigned long long)selectionMode;
-(void)setSelectionMode:(unsigned long long)arg1 ;
@end
