/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://www.developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTNRStatus.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

API_AVAILABLE(ios(14.0))
@interface CTNRStatus : NSObject <NSCopying, NSSecureCoding> {

    BOOL _saSwitchVisible;
    BOOL _saSwitchConfigurable;
    BOOL _saDisabled;
    BOOL _nsaDisabled;
    unsigned long long _saDisabledReasonMask;
    unsigned long long _nsaDisabledReasonMask;
}
@property (assign,getter=isSASwitchVisible,nonatomic) BOOL saSwitchVisible;                        //@synthesize saSwitchVisible=_saSwitchVisible - In the implementation block
@property (assign,getter=isSASwitchConfigurable,nonatomic) BOOL saSwitchConfigurable;              //@synthesize saSwitchConfigurable=_saSwitchConfigurable - In the implementation block
@property (assign,getter=isSADisabled,nonatomic) BOOL saDisabled;                                  //@synthesize saDisabled=_saDisabled - In the implementation block
@property (assign,nonatomic) unsigned long long saDisabledReasonMask;                              //@synthesize saDisabledReasonMask=_saDisabledReasonMask - In the implementation block
@property (assign,getter=isNSADisabled,nonatomic) BOOL nsaDisabled;                                //@synthesize nsaDisabled=_nsaDisabled - In the implementation block
@property (assign,nonatomic) unsigned long long nsaDisabledReasonMask;                             //@synthesize nsaDisabledReasonMask=_nsaDisabledReasonMask - In the implementation block
+(BOOL)supportsSecureCoding;
+(id)default;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setNsaDisabled:(BOOL)arg1 ;
-(id)initWithSASwitchVisible:(BOOL)arg1 saSwitchConfigurable:(BOOL)arg2 saDisabledByBaseband:(BOOL)arg3 saDisabledReasonMask:(unsigned long long)arg4 nsaDisabledByBaseband:(BOOL)arg5 nsaDisabledReasonMask:(unsigned long long)arg6 ;
-(BOOL)isNSADisabled;
-(BOOL)isSADisabled;
-(BOOL)isSASwitchConfigurable;
-(BOOL)isSASwitchVisible;
-(unsigned long long)nsaDisabledReasonMask;
-(unsigned long long)saDisabledReasonMask;
-(void)setNsaDisabledReasonMask:(unsigned long long)arg1 ;
-(void)setSaDisabled:(BOOL)arg1 ;
-(void)setSaDisabledReasonMask:(unsigned long long)arg1 ;
-(void)setSaSwitchConfigurable:(BOOL)arg1 ;
-(void)setSaSwitchVisible:(BOOL)arg1 ;
@end
