/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://www.developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTPhoneBookEntry.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

@class NSString;

/// SIM卡存储的联系人的数据对象
@interface CTPhoneBookEntry : NSObject <NSCopying, NSSecureCoding> {

    BOOL _isHidden;        // 是否隐藏
    NSString* _name;       // 名字
    NSString* _number;     // 电话号码
    NSString* _altNumber;  // 第二号码（USIM 扩展字段）
    NSString* _altText;    // 第二号码描述文本
    NSString* _email;      // Email
    NSString* _group;      // 分组标签
}
@property (assign,nonatomic) BOOL isHidden;                     //@synthesize isHidden=_isHidden - In the implementation block
@property (nonatomic,retain) NSString * name;                   //@synthesize name=_name - In the implementation block
@property (nonatomic,retain) NSString * number;                 //@synthesize number=_number - In the implementation block
@property (nonatomic,retain) NSString * altNumber;              //@synthesize altNumber=_altNumber - In the implementation block
@property (nonatomic,retain) NSString * altText;                //@synthesize altText=_altText - In the implementation block
@property (nonatomic,retain) NSString * email;                  //@synthesize email=_email - In the implementation block
@property (nonatomic,retain) NSString * group;                  //@synthesize group=_group - In the implementation block
+(BOOL)supportsSecureCoding;
-(void)setGroup:(NSString *)arg1 ;
-(NSString *)group;
-(NSString *)email;
-(void)setIsHidden:(BOOL)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isHidden;
-(void)setEmail:(NSString *)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(id)description;
-(NSString *)number;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setNumber:(NSString *)arg1 ;
-(NSString *)altText;
-(NSString *)altNumber;
-(void)setAltNumber:(NSString *)arg1 ;
-(void)setAltText:(NSString *)arg1 ;
@end
