/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://www.developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTQoS.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

@class NSNumber, NSArray;

@interface CTQoS : NSObject <NSCopying, NSSecureCoding> {

    NSNumber* _qci;
    NSNumber* _bitRateMax;
    NSNumber* _bitRateMin;
    NSArray* _filters;
}
@property (nonatomic,retain) NSNumber * qci;                     //@synthesize qci=_qci - In the implementation block
@property (nonatomic,retain) NSNumber * bitRateMax;              //@synthesize bitRateMax=_bitRateMax - In the implementation block
@property (nonatomic,retain) NSNumber * bitRateMin;              //@synthesize bitRateMin=_bitRateMin - In the implementation block
@property (nonatomic,retain) NSArray * filters;                  //@synthesize filters=_filters - In the implementation block
@property (nonatomic,readonly) NSNumber * gbr;
+(BOOL)supportsSecureCoding;
-(void)setFilters:(NSArray *)arg1 ;
-(NSArray *)filters;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSNumber *)gbr;
-(void)setQci:(NSNumber *)arg1 ;
-(NSNumber *)qci;
-(NSNumber *)bitRateMax;
-(NSNumber *)bitRateMin;
-(void)setBitRateMax:(NSNumber *)arg1 ;
-(void)setBitRateMin:(NSNumber *)arg1 ;
@end

