/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTRatSelection.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

@class NSString;
API_AVAILABLE(ios(14.0))
@interface CTRatSelection : NSObject <NSCopying, NSSecureCoding> {

    unsigned char _mask;
    NSString* _selection;
    NSString* _preferred;
}
@property (assign,nonatomic) unsigned char mask;                //@synthesize mask=_mask - In the implementation block
@property (nonatomic,retain) NSString * selection;              //@synthesize selection=_selection - In the implementation block
@property (nonatomic,retain) NSString * preferred;              //@synthesize preferred=_preferred - In the implementation block
+(BOOL)supportsSecureCoding;
-(NSString *)selection;
-(void)setSelection:(NSString *)arg1 ;
-(void)setPreferred:(NSString *)arg1 ;
-(void)setMask:(unsigned char)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(NSString *)preferred;
-(id)description;
-(unsigned char)mask;
-(id)copyWithZone:(NSZone*)arg1 ;
@end
