/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTRegistrationDisplayStatus.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

@class NSString;
// 网络注册状态的头文件
@interface CTRegistrationDisplayStatus : NSObject <NSCopying, NSSecureCoding> {

    BOOL _isInHomeCountry;
    BOOL _changedDueToSimRemoval;
    BOOL _isRegistrationForcedHome;
    NSString* _registrationDisplayStatus;
}
@property (nonatomic,retain) NSString * registrationDisplayStatus;              //@synthesize registrationDisplayStatus=_registrationDisplayStatus - In the implementation block
@property (assign,nonatomic) BOOL isInHomeCountry;                              //@synthesize isInHomeCountry=_isInHomeCountry - In the implementation block
@property (assign,nonatomic) BOOL changedDueToSimRemoval;                       //@synthesize changedDueToSimRemoval=_changedDueToSimRemoval - In the implementation block
@property (assign,nonatomic) BOOL isRegistrationForcedHome;                     //@synthesize isRegistrationForcedHome=_isRegistrationForcedHome - In the implementation block
+(BOOL)supportsSecureCoding;
-(void)setIsRegistrationForcedHome:(BOOL)arg1 ;
-(void)setRegistrationDisplayStatus:(NSString *)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(NSString *)registrationDisplayStatus; // 注册状态
-(id)initWithCoder:(id)arg1 ;
-(BOOL)changedDueToSimRemoval; // 因SIM卡改变导致注册状态发生改变
-(void)setIsInHomeCountry:(BOOL)arg1 ;
-(BOOL)isInHomeCountry; // 是否在自己网络所在的国家/地区
-(BOOL)isRegistrationForcedHome; // 是否强制注册为本地网络
-(void)setChangedDueToSimRemoval:(BOOL)arg1 ;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

