/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://www.developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTServiceDescriptorContainer.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>
#import "CTServiceDescriptor.h"

@class NSArray;
@class CTServiceDescriptor;

@interface CTServiceDescriptorContainer : NSObject <NSCopying, NSSecureCoding> {

    NSArray* _descriptors;
}
@property (nonatomic,retain) NSArray<CTServiceDescriptor *> * descriptors;              //@synthesize descriptors=_descriptors - In the implementation block

+(BOOL)supportsSecureCoding;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithDescriptors:(id)arg1 ;
-(NSArray<CTServiceDescriptor *> *)descriptors; // 获取CTServiceDescriptor列表
-(BOOL)isEqual:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)setDescriptors:(NSArray<CTServiceDescriptor *> *)descriptors;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
@end
