/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:38 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://www.developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTSimHardwareInfo.h
*/

//#import <CoreTelephony/NSSecureCoding.h>

// SIM卡硬件信息
API_AVAILABLE(ios(15.0))
@interface CTSimHardwareInfo : NSObject <NSSecureCoding> {

    long long _hardwareType;
    long long _simLocation;
}
@property (assign,nonatomic) long long hardwareType;              //@synthesize hardwareType=_hardwareType - In the implementation block
@property (assign,nonatomic) long long simLocation;               //@synthesize simLocation=_simLocation - In the implementation block
+(BOOL)supportsSecureCoding;
-(long long)hardwareType; // SIM卡类型 实体卡或者eSIM
-(void)encodeWithCoder:(id)arg1 ;
-(void)setHardwareType:(long long)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)description;
-(void)setSimLocation:(long long)arg1 ;
-(id)initWithHardwareInfo:(long long)arg1 simLocation:(long long)arg2 ;
-(long long)simLocation; // SIM卡所在位置 正面、背面、eSIM
@end
