/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://www.developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTSignalStrengthMeasurements.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

@class NSNumber;
API_AVAILABLE(ios(13.0))
@interface CTSignalStrengthMeasurements : NSObject <NSCopying, NSSecureCoding> {

    NSNumber* _rssi;
    NSNumber* _rscp;  // 3G网络信号参考值
    NSNumber* _ecn0;  // 3G网络信噪比
    NSNumber* _rsrp;  // 4G/5G参考信号值
    NSNumber* _rsrq;
    NSNumber* _snr;   // 4G/5G网络信噪比
    NSNumber* _ecio;
    NSNumber* _rxagc;
}
@property (nonatomic,retain) NSNumber * rssi;               //@synthesize rssi=_rssi - In the implementation block
@property (nonatomic,retain) NSNumber * rscp;               //@synthesize rscp=_rscp - In the implementation block
@property (nonatomic,retain) NSNumber * ecn0;               //@synthesize ecn0=_ecn0 - In the implementation block
@property (nonatomic,retain) NSNumber * rsrp;               //@synthesize rsrp=_rsrp - In the implementation block
@property (nonatomic,retain) NSNumber * rsrq;               //@synthesize rsrq=_rsrq - In the implementation block
@property (nonatomic,retain) NSNumber * snr;                //@synthesize snr=_snr - In the implementation block
@property (nonatomic,retain) NSNumber * ecio;               //@synthesize ecio=_ecio - In the implementation block
@property (nonatomic,retain) NSNumber * rxagc;              //@synthesize rxagc=_rxagc - In the implementation block

+(BOOL)supportsSecureCoding;
-(NSNumber *)snr;
-(void)setSnr:(NSNumber *)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(NSNumber *)rssi;
-(id)initWithCoder:(id)arg1 ;
-(void)setRssi:(NSNumber *)arg1 ;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSNumber *)ecio;
-(NSNumber *)ecn0;
-(NSNumber *)rscp;
-(NSNumber *)rsrp;
-(NSNumber *)rsrq;
-(NSNumber *)rxagc;
-(void)setEcio:(NSNumber *)arg1 ;
-(void)setEcn0:(NSNumber *)arg1 ;
-(void)setRscp:(NSNumber *)arg1 ;
-(void)setRsrp:(NSNumber *)arg1 ;
-(void)setRsrq:(NSNumber *)arg1 ;
-(void)setRxagc:(NSNumber *)arg1 ;
@end
