/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://www.developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTTetheringStatus.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

@class NSNumber, CTDataConnectionAvailabilityStatus, CTDataConnectionStatus, CTXPCServiceSubscriptionContext;

API_AVAILABLE(ios(15.0))
@interface CTTetheringStatus : NSObject <NSCopying, NSSecureCoding> {

    NSNumber* _carrierEnabled; // 运营商是否允许开启热点 可能为nil
    NSNumber* _userAuthenticated; // 热点已验证允许 可能为nil
    NSNumber* _asserted; // 热点开关是否已经打开 可能为nil
    NSNumber* _activationFailure; // 可能为nil
    NSNumber* _misPdpMaxHosts; // 可能为nil
    CTDataConnectionAvailabilityStatus* _connectionAvailabilityStatus; // 可能为nil
    CTDataConnectionStatus* _connectionStatus; // 可能为nil
    CTXPCServiceSubscriptionContext* _context;
}
@property (nonatomic,retain) NSNumber * carrierEnabled;                                                      //@synthesize carrierEnabled=_carrierEnabled - In the implementation block
@property (nonatomic,retain) NSNumber * userAuthenticated;                                                   //@synthesize userAuthenticated=_userAuthenticated - In the implementation block
@property (nonatomic,retain) NSNumber * asserted;                                                            //@synthesize asserted=_asserted - In the implementation block
@property (nonatomic,retain) NSNumber * activationFailure;                                                   //@synthesize activationFailure=_activationFailure - In the implementation block
@property (nonatomic,retain) NSNumber * misPdpMaxHosts;                                                      //@synthesize misPdpMaxHosts=_misPdpMaxHosts - In the implementation block
@property (nonatomic,retain) CTDataConnectionAvailabilityStatus * connectionAvailabilityStatus;              //@synthesize connectionAvailabilityStatus=_connectionAvailabilityStatus - In the implementation block
@property (nonatomic,retain) CTDataConnectionStatus * connectionStatus;                                      //@synthesize connectionStatus=_connectionStatus - In the implementation block
@property (nonatomic,retain) CTXPCServiceSubscriptionContext * context;                                      //@synthesize context=_context - In the implementation block
+(BOOL)supportsSecureCoding;
-(NSNumber *)misPdpMaxHosts;
-(CTXPCServiceSubscriptionContext *)context;
-(CTDataConnectionStatus *)connectionStatus;
-(void)setUserAuthenticated:(NSNumber *)arg1 ;
-(void)setActivationFailure:(NSNumber *)arg1 ;
-(NSNumber *)carrierEnabled;
-(void)setContext:(CTXPCServiceSubscriptionContext *)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)setConnectionStatus:(CTDataConnectionStatus *)arg1 ;
-(NSNumber *)asserted;
-(void)setAsserted:(NSNumber *)arg1 ;
-(NSNumber *)activationFailure;
-(id)initWithCoder:(id)arg1 ;
-(NSNumber *)userAuthenticated;
-(void)setMisPdpMaxHosts:(NSNumber *)arg1 ;
-(CTDataConnectionAvailabilityStatus *)connectionAvailabilityStatus;
-(void)setConnectionAvailabilityStatus:(CTDataConnectionAvailabilityStatus *)arg1 ;
-(id)description;
-(void)setCarrierEnabled:(NSNumber *)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
@end
