/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTTelephonyNetworkInfo.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/CoreTelephonyClientDataDelegateInternal.h>
//#import <CoreTelephony/CoreTelephonyClientRegistrationDelegateInternal.h>

#import <CoreTelephony/CTTelephonyNetworkInfo.h>

#import "CoreTelephonyClientDataDelegateInternal.h"
#import "CoreTelephonyClientRegistrationDelegateInternal.h"

@protocol CTTelephonyNetworkInfoDelegate;
@class CoreTelephonyClient, CTTelephonyNetworkInfoDelegatePlus, CTServiceDescriptorContainer, NSMutableDictionary, NSString, CTCarrier, NSDictionary;

//@interface CTTelephonyNetworkInfo : NSObject <CoreTelephonyClientDataDelegateInternal, CoreTelephonyClientRegistrationDelegateInternal> {
@interface CTTelephonyNetworkInfo (Private) {

//    CoreTelephonyClient* _client;
//    CoreTelephonyClient* _clientPlus;
//    CTTelephonyNetworkInfoDelegatePlus* _delegatePlus;
//    id<CTTelephonyNetworkInfoDelegate> _delegate;
//    /*^block*/id _serviceSubscriberCellularProvidersDidUpdateNotifier;
//    /*^block*/id _subscriberCellularProviderDidUpdateNotifier;
//    BOOL _initialized;
//    BOOL _dataBearerCellularTechnologyInitialized;
//    BOOL _nrFrequencyRangeInitialized;
//    int _cachedDataBearerCellularTechnology;
//    unsigned _cachedNrFrequencyRange;
//    CTServiceDescriptorContainer* _descriptors;
//    NSMutableDictionary* _serviceSubscriberCellularProviders;
//    NSMutableDictionary* _cachedCurrentRadioAccessTechnology;
//    NSMutableDictionary* _cachedSignalStrength;
//    NSMutableDictionary* _cachedCellIds;
//    queue* _clientQueue;
}
@property (retain) NSMutableDictionary * serviceSubscriberCellularProviders;                           //@synthesize serviceSubscriberCellularProviders=_serviceSubscriberCellularProviders - In the implementation block
@property (retain) NSMutableDictionary * cachedCurrentRadioAccessTechnology;                           //@synthesize cachedCurrentRadioAccessTechnology=_cachedCurrentRadioAccessTechnology - In the implementation block
@property (retain) NSMutableDictionary * cachedSignalStrength;                                         //@synthesize cachedSignalStrength=_cachedSignalStrength - In the implementation block
@property (retain) NSMutableDictionary * cachedCellIds;                                                //@synthesize cachedCellIds=_cachedCellIds - In the implementation block
@property (assign) int cachedDataBearerCellularTechnology;                                             //@synthesize cachedDataBearerCellularTechnology=_cachedDataBearerCellularTechnology - In the implementation block
@property (assign) BOOL dataBearerCellularTechnologyInitialized;                                       //@synthesize dataBearerCellularTechnologyInitialized=_dataBearerCellularTechnologyInitialized - In the implementation block
@property (assign) unsigned cachedNrFrequencyRange;                                                    //@synthesize cachedNrFrequencyRange=_cachedNrFrequencyRange - In the implementation block
@property (assign) BOOL nrFrequencyRangeInitialized;                                                   //@synthesize nrFrequencyRangeInitialized=_nrFrequencyRangeInitialized - In the implementation block
@property (readonly) CTServiceDescriptorContainer * descriptors;                                       //@synthesize descriptors=_descriptors - In the implementation block
//@property (assign) queue* clientQueue;                                                                 //@synthesize clientQueue=_clientQueue - In the implementation block
@property (copy,readonly) NSString * dataServiceIdentifier;
//@property (__weak) id<CTTelephonyNetworkInfoDelegate> delegate;
@property (retain,readonly) CTCarrier * subscriberCellularProvider;
@property (nonatomic,copy) id serviceSubscriberCellularProvidersDidUpdateNotifier;                     //@synthesize serviceSubscriberCellularProvidersDidUpdateNotifier=_serviceSubscriberCellularProvidersDidUpdateNotifier - In the implementation block
@property (nonatomic,copy) id subscriberCellularProviderDidUpdateNotifier;
@property (nonatomic,retain,readonly) NSDictionary * serviceCurrentRadioAccessTechnology;
@property (nonatomic,retain,readonly) NSString * currentRadioAccessTechnology;
//@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
-(id)init;
-(id)initWithClient:(CoreTelephonyClient *)client ;
-(void)dealloc;
-(id<CTTelephonyNetworkInfoDelegate>)delegate API_AVAILABLE(ios(17.0));
-(/*^block*/id)serviceSubscribersCellularProviderDidUpdateNotifier;
-(void)carrierBundleChange:(id)arg1 ;

-(NSMutableDictionary *)cachedCellIds;
-(NSMutableDictionary *)cachedCurrentRadioAccessTechnology;
-(NSString *)getFirstCellId;
-(id)serviceCellId;
-(id)serviceSignalStrength;
-(id)radioAccessTechnology;
-(NSString *)currentRadioAccessTechnology; // 获取slot1的网络类型 并不是当前的网络类型
-(NSString *)dataServiceIdentifier; // 首选网络的卡槽编号
-(int)cachedDataBearerCellularTechnology;
-(BOOL)getAllowsVOIP:(BOOL *)result forContext:(CTXPCServiceSubscriptionContext *)context withError:(NSError **)error ;
-(NSDictionary *)serviceCurrentRadioAccessTechnology; // 公开方法获取网络类型
-(BOOL)nrFrequencyRangeInitialized API_AVAILABLE(ios(15.0)); // NR频率范围状态已就绪;
-(void)tryInitNrFrequencyRange API_AVAILABLE(ios(15.0));
-(void)queryNrFrequencyRange API_AVAILABLE(ios(15.0)); // 查询NR频率范围
-(NSString *)currentNrFrequencyRange API_AVAILABLE(ios(15.0)); // NR频率范围
-(unsigned)cachedNrFrequencyRange API_AVAILABLE(ios(15.0));
-(NSMutableDictionary *)serviceSubscriberCellularProviders;
-(CTServiceDescriptorContainer *)descriptors; // 获取服务描述列表 用这个获取一共有几个卡槽
-(id)cellId;
-(id)subscriberCellularProviderDidUpdateNotifier;
-(id)serviceSubscriberCellularProvidersDidUpdateNotifier;
-(void)querySignalStrengthForDescriptor:(CTServiceDescriptor *)descriptor;
-(NSString *)currentDataBearerTechnology; // 当前使用的网络类型
-(NSMutableDictionary *)cachedSignalStrength;
-(BOOL)getMobileCountryCode:(id)arg1 andIsoCountryCode:(id)arg2 forContext:(id)arg3 withError:(id*)arg4 ; // 获取MCC
-(BOOL)getMobileNetworkCode:(id)arg1 forContext:(id)arg2 withError:(id*)arg3 ; // 获取MNC
-(BOOL)getCarrierName:(id)carrierName forContext:(id)arg2 withError:(id*)arg3 ;
-(CTCarrier *)subscriberCellularProvider; // 获取卡槽1的CTCarrier实例
-(NSDictionary<NSString *, NSNumber *> *)signalStrength;
-(BOOL)dataBearerCellularTechnologyInitialized;
-(BOOL)updateNetworkInfoAndShouldNotifyClient:(BOOL*)arg1 forContext:(id)arg2 ;

-(void)setServiceSubscriberCellularProvidersDidUpdateNotifier:(id)arg1 ;
//-(queue*)clientQueue;
-(void)currentDataServiceDescriptorChanged:(id)arg1 ;
//-(void)setClientQueue:(queue*)arg1 ;
-(void)updateLegacyRat:(id)arg1 ;
-(void)setServiceSubscriberCellularProviders:(NSMutableDictionary *)arg1 ;
-(void)setServiceSubscriberCellularProviderDidUpdateNotifier:(/*^block*/id)arg1 ;
-(void)updateNrFrequencyRange:(unsigned)arg1 ;
-(void)cellChanged:(id)arg1 cell:(id)arg2 ;
-(void)regDataModeChanged:(id)arg1 dataMode:(int)arg2 ;
-(void)signalStrengthChanged:(id)arg1 info:(id)arg2 ;
-(void)postNotificationIfReady:(id)arg1 object:(id)arg2 ;
-(void)queryCellIds;
-(void)queryDataBearer;
-(void)queryCTSignalStrength;
-(void)setCachedNrFrequencyRange:(unsigned)arg1 ;

-(void)setDataBearerCellularTechnologyInitialized:(BOOL)arg1 ;
-(void)tryInitDelegatePlus;
-(void)setDelegate:(id<CTTelephonyNetworkInfoDelegate>)arg1 API_AVAILABLE(ios(13.0));
-(void)dataStatusUpdate:(id)arg1 dataStatusInfo:(id)arg2 ;
-(void)updateCellId:(id)arg1 forDescriptor:(id)arg2 ;
-(void)queryRatForDescriptor:(id)arg1 ;
-(void)setCachedCellIds:(NSMutableDictionary *)arg1 ;
-(void)setCachedDataBearerCellularTechnology:(int)arg1 ;
-(void)updateRat:(id)arg1 descriptor:(id)arg2 ;
-(void)setCachedSignalStrength:(NSMutableDictionary *)arg1 ;
-(void)updateSignalStrength:(id)arg1 descriptor:(id)arg2 ;
-(void)setCachedCurrentRadioAccessTechnology:(NSMutableDictionary *)arg1 ;
-(void)updateDataBearer:(int)arg1 ;
-(void)tryInitPrivateFunctionality;
-(void)setNrFrequencyRangeInitialized:(BOOL)arg1 ;
-(void)setSubscriberCellularProviderDidUpdateNotifier:(id)arg1 ;
-(void)tryInitDataBearer;
-(void)queryRat;
@end
