/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTXPCContexts.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

#import "CTXPCContextInfo.h"

@class NSArray, NSUUID;

@interface CTXPCContexts : NSObject <NSCopying, NSSecureCoding> {

    NSArray* _subscriptions; // 无SIM卡为nil
    NSUUID* _dataPreferred; // 无SIM卡为nil
    NSUUID* _voicePreferred; // 无SIM卡为nil
}
@property (nonatomic,retain) NSArray<CTXPCContextInfo *> * subscriptions;              //@synthesize subscriptions=_subscriptions - In the implementation block
@property (nonatomic,retain) NSUUID * dataPreferred;               //@synthesize dataPreferred=_dataPreferred - In the implementation block
@property (nonatomic,retain) NSUUID * voicePreferred;              //@synthesize voicePreferred=_voicePreferred - In the implementation block
+(BOOL)supportsSecureCoding;
-(NSArray <CTXPCContextInfo *>*)subscriptions;
-(void)setSubscriptions:(NSArray <CTXPCContextInfo *>*)context;
-(NSUUID *)voicePreferred;
-(CTXPCContextInfo *)findForSlot:(long long)slotID;
-(void)encodeWithCoder:(id)arg1 ;
-(id)findForUuid:(id)arg1 ;
-(void)setDataPreferred:(NSUUID *)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(NSUUID *)dataPreferred;
-(id)description;
-(void)setVoicePreferred:(NSUUID *)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)findForAccount:(id)arg1 ;
@end
