/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37 PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
  https://www.developer.limneos.net/index.php?ios=17.1&framework=CoreTelephony.framework&header=CTXPCServiceSubscriptionInfo.h
*/

//#import <CoreTelephony/CoreTelephony-Structs.h>
//#import <CoreTelephony/NSCopying.h>
//#import <CoreTelephony/NSSecureCoding.h>

#import "CTXPCServiceSubscriptionContext.h"

@class NSArray;

@interface CTXPCServiceSubscriptionInfo : NSObject <NSCopying, NSSecureCoding> {

    NSArray * _subscriptions;
    NSArray * _subscriptionsInUse;
    NSArray * _subscriptionsValid;
}
@property (nonatomic,retain) NSArray<CTXPCServiceSubscriptionContext *> * subscriptions;                   //@synthesize subscriptions=_subscriptions - In the implementation block
@property (nonatomic,retain) NSArray<CTXPCServiceSubscriptionContext *> * subscriptionsInUse;              //@synthesize subscriptionsInUse=_subscriptionsInUse - In the implementation block
@property (nonatomic,retain) NSArray<CTXPCServiceSubscriptionContext *> * subscriptionsValid;              //@synthesize subscriptionsValid=_subscriptionsValid - In the implementation block
+(BOOL)supportsSecureCoding;
-(NSArray<CTXPCServiceSubscriptionContext *> *)subscriptions; // 所有的Context
-(void)setSubscriptions:(NSArray<CTXPCServiceSubscriptionContext *> *)contexts ;
-(NSArray<CTXPCServiceSubscriptionContext *> *)subscriptionsValid;
-(void)encodeWithCoder:(id)arg1 ;
-(NSArray<CTXPCServiceSubscriptionContext *> *)subscriptionsInUse;
-(BOOL)isEqual:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)setSubscriptionsInUse:(NSArray<CTXPCServiceSubscriptionContext *> *)contexts ;
-(void)setSubscriptionsValid:(NSArray<CTXPCServiceSubscriptionContext *> *)contexts ;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)redactedDescription;
@end
